/// Lexical token produced by the Functional Pascal lexer.
#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    // Keywords (58)
    Program,
    Unit,
    Uses,
    Const,
    Var,
    Mutable,
    Function,
    Procedure,
    Begin,
    End,
    Return,
    If,
    Then,
    Else,
    Case,
    Of,
    For,
    To,
    Downto,
    In,
    Do,
    While,
    Repeat,
    Until,
    And,
    Or,
    Not,
    Xor,
    Div,
    Mod,
    Shl,
    Shr,
    True,
    False,
    Type,
    Record,
    Enum,
    Array,
    Forward,
    Panic,
    Break,
    Continue,
    Public,
    Private,
    Result,
    OptionKw,
    Ok,
    Error,
    Some,
    None,
    Try,
    Go,
    Channel,
    Select,
    From,
    Dict,
    Ref,
    New,
    With,

    // Literals
    Integer(i64),
    Real(f64),
    Str(String),

    // Identifier
    Ident(String),

    // Symbols
    ColonAssign,
    DotDot,
    NotEqual,
    LessEqual,
    GreaterEqual,
    Colon,
    Semicolon,
    Comma,
    Dot,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Plus,
    Minus,
    Star,
    Slash,
    Equal,
    Less,
    Greater,

    // End of file
    Eof,
}

impl Token {
    pub fn from_ident(raw: String) -> Token {
        match raw.to_ascii_lowercase().as_str() {
            "program" => Token::Program,
            "unit" => Token::Unit,
            "uses" => Token::Uses,
            "const" => Token::Const,
            "var" => Token::Var,
            "mutable" => Token::Mutable,
            "function" => Token::Function,
            "procedure" => Token::Procedure,
            "begin" => Token::Begin,
            "end" => Token::End,
            "return" => Token::Return,
            "if" => Token::If,
            "then" => Token::Then,
            "else" => Token::Else,
            "case" => Token::Case,
            "of" => Token::Of,
            "for" => Token::For,
            "to" => Token::To,
            "downto" => Token::Downto,
            "in" => Token::In,
            "do" => Token::Do,
            "while" => Token::While,
            "repeat" => Token::Repeat,
            "until" => Token::Until,
            "and" => Token::And,
            "or" => Token::Or,
            "not" => Token::Not,
            "xor" => Token::Xor,
            "div" => Token::Div,
            "mod" => Token::Mod,
            "shl" => Token::Shl,
            "shr" => Token::Shr,
            "true" => Token::True,
            "false" => Token::False,
            "type" => Token::Type,
            "record" => Token::Record,
            "enum" => Token::Enum,
            "array" => Token::Array,
            "forward" => Token::Forward,
            "panic" => Token::Panic,
            "break" => Token::Break,
            "continue" => Token::Continue,
            "public" => Token::Public,
            "private" => Token::Private,
            "result" => Token::Result,
            "option" => Token::OptionKw,
            "ok" => Token::Ok,
            "error" => Token::Error,
            "some" => Token::Some,
            "none" => Token::None,
            "try" => Token::Try,
            "go" => Token::Go,
            "channel" => Token::Channel,
            "select" => Token::Select,
            "from" => Token::From,
            "dict" => Token::Dict,
            "ref" => Token::Ref,
            "new" => Token::New,
            "with" => Token::With,
            _ => Token::Ident(raw),
        }
    }
}
