//! Concatenates `src/intrinsic/tui/variants/*.inc` into a generated `TuiIntrinsic` enum.

use std::env;
use std::error::Error;
use std::fs;
use std::path::Path;

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let variants_dir = manifest_dir.join("src/intrinsic/tui/variants");
    println!("cargo:rerun-if-changed={}", variants_dir.display());

    let fragments = [
        "session.inc",
        "chrome.inc",
        "test_host.inc",
        "widgets.inc",
        "bridge.inc",
    ];

    let mut variants = String::new();
    for fragment in fragments {
        let path = variants_dir.join(fragment);
        println!("cargo:rerun-if-changed={}", path.display());
        let body = fs::read_to_string(&path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        if !variants.is_empty() && !variants.ends_with('\n') {
            variants.push('\n');
        }
        variants.push_str(body.trim_end());
        variants.push('\n');
    }

    let generated = format!(
        r#"// @generated by build.rs — do not edit.
use num_enum::TryFromPrimitive;

/// Intrinsics for `Std.Tui.*`.
///
/// **Documentation:** `docs/pascal/std/tui/session.md`, `docs/pascal/std/tui/app/README.md`
#[derive(Debug, Clone, Copy, PartialEq, Eq, TryFromPrimitive)]
#[repr(u16)]
pub enum TuiIntrinsic {{
{variants}    // **375..=377** are `Std.Test` screen/view assertions; **378** is `Std.Test.PushReadLn` (see `TestIntrinsic`).
    // Note: **348..=355** are owned by `Std.Test` (`TestIntrinsic`).
}}
"#
    );

    let out_dir = env::var("OUT_DIR")?;
    fs::write(Path::new(&out_dir).join("tui_intrinsic.rs"), generated)?;
    Ok(())
}
