//! Current syntax emitted for intrinsic editor declarations.

use super::DocumentationRow;
use super::documentation::{
    default_value, documentation_row, parameter_description, render_documentation,
};
use fpas_sema::{IntrinsicStdSymbol, IntrinsicStdSymbolKind, ParamTy, Ty};
use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;

/// Render one unit with individually exported declarations and named closers.
pub(super) fn render_unit(
    unit: &str,
    symbols: &[IntrinsicStdSymbol],
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<String, String> {
    let mut output = format!(
        "unit {unit};\n\n// Generated by `cargo run -p fpas-sema --example export_intrinsic_std_api`.\n// Edit the Rust registry and `docs/pascal/std/`, then regenerate this editor declaration surface.\n// Runtime behavior is implemented by the compiler, VM, or Rust standard-library crate.\n"
    );
    let prefix = format!("{unit}.");
    let mut by_name = symbols
        .iter()
        .map(|symbol| {
            (
                symbol.qualified_name.trim_start_matches(&prefix).to_owned(),
                symbol,
            )
        })
        .collect::<BTreeMap<_, _>>();

    render_constants(&mut output, unit, &mut by_name, documentation)?;
    render_types(&mut output, unit, &mut by_name, documentation)?;
    render_routines(&mut output, unit, &by_name, documentation);
    output.push_str("\nend unit;\n");
    Ok(super::qualifiers::qualify(unit, &output))
}

fn render_constants(
    output: &mut String,
    unit: &str,
    symbols: &mut BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<(), String> {
    let names = symbols
        .iter()
        .filter(|(_, symbol)| symbol.kind == IntrinsicStdSymbolKind::Constant)
        .map(|(name, _)| name.clone())
        .collect::<Vec<_>>();
    if names.is_empty() {
        return Ok(());
    }
    for name in names {
        let symbol = take_symbol(symbols, &name, "constant")?;
        render_documentation(output, unit, &name, symbol, documentation, "  ");
        let _ = writeln!(
            output,
            "public const {name}: {} := {};",
            symbol.ty,
            default_value(&symbol.ty)
        );
    }
    Ok(())
}

fn render_types(
    output: &mut String,
    unit: &str,
    symbols: &mut BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<(), String> {
    let type_names = symbols
        .iter()
        .filter(|(name, symbol)| symbol.kind == IntrinsicStdSymbolKind::Type && !name.contains('.'))
        .map(|(name, _)| name.clone())
        .collect::<Vec<_>>();
    if type_names.is_empty() {
        return Ok(());
    }
    for name in type_names {
        let symbol = take_symbol(symbols, &name, "type")?;
        render_documentation(output, unit, &name, symbol, documentation, "  ");
        match &symbol.ty {
            Ty::Enum(value) => render_enum(output, unit, &name, value),
            Ty::Record(value) => {
                let member_names = symbols
                    .keys()
                    .filter(|candidate| candidate.starts_with(&format!("{name}.")))
                    .cloned()
                    .collect::<Vec<_>>();
                render_record(
                    output,
                    unit,
                    &name,
                    value,
                    &member_names,
                    symbols,
                    documentation,
                )?;
            }
            _ => {
                let _ = writeln!(output, "public type {name} = {};", symbol.ty);
            }
        }
    }
    Ok(())
}

fn render_enum(output: &mut String, _unit: &str, name: &str, value: &fpas_sema::EnumTy) {
    let _ = writeln!(output, "public type {name} = enum");
    for variant in &value.variants {
        let _ = writeln!(output, "    // `{}` enum member.", variant.name);
        if !variant.fields.is_empty() {
            output.push_str("    //\n    // Parameters:\n");
            for (field, ty) in &variant.fields {
                let _ = writeln!(
                    output,
                    "    // - `{field}`: {}",
                    parameter_description(
                        field,
                        &format!("{name}.{}", variant.name),
                        Some(&ty.to_string())
                    )
                );
            }
        }
        if !is_source_identifier(&variant.name) {
            continue;
        }
        let separator = ";";
        if variant.fields.is_empty() {
            let _ = writeln!(output, "    {}{separator}", variant.name);
        } else {
            let fields = variant
                .fields
                .iter()
                .map(|(field, ty)| format!("{field}: {ty}"))
                .collect::<Vec<_>>()
                .join("; ");
            let _ = writeln!(output, "    {}({fields}){separator}", variant.name);
        }
    }
    output.push_str("end enum;\n");
}

fn is_source_identifier(name: &str) -> bool {
    fpas_lexer::lex(name)
        .0
        .first()
        .is_some_and(|token| matches!(token.token, fpas_lexer::Token::Ident(_)))
}

fn render_record(
    output: &mut String,
    unit: &str,
    name: &str,
    value: &fpas_sema::RecordTy,
    member_names: &[String],
    symbols: &mut BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<(), String> {
    let _ = writeln!(output, "public type {name} = record");
    if value.fields.is_empty() && member_names.is_empty() {
        output.push_str("    // Compiler-owned storage for this opaque handle.\n");
        output.push_str("    _IntrinsicHandle: integer;\n");
    } else {
        for (field, ty) in &value.fields {
            let _ = writeln!(output, "    public {field}: {ty};");
        }
    }
    for member_name in member_names {
        let symbol = take_symbol(symbols, member_name, "record member")?;
        if symbol.kind == IntrinsicStdSymbolKind::EnumMember {
            continue;
        }
        let short_name = member_name.rsplit('.').next().unwrap_or(member_name);
        render_documentation(output, unit, member_name, symbol, documentation, "    ");
        render_routine(
            output,
            short_name,
            symbol,
            documentation_row(unit, member_name, documentation),
            "    ",
            true,
        );
    }
    output.push_str("end record;\n");
    Ok(())
}

fn take_symbol<'a>(
    symbols: &mut BTreeMap<String, &'a IntrinsicStdSymbol>,
    name: &str,
    kind: &str,
) -> Result<&'a IntrinsicStdSymbol, String> {
    symbols
        .remove(name)
        .ok_or_else(|| format!("catalog {kind} `{name}` is missing"))
}

fn render_routines(
    output: &mut String,
    unit: &str,
    symbols: &BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) {
    for (name, symbol) in symbols {
        if !matches!(
            symbol.kind,
            IntrinsicStdSymbolKind::Function | IntrinsicStdSymbolKind::Procedure
        ) || name.contains('.')
        {
            continue;
        }
        output.push('\n');
        render_documentation(output, unit, name, symbol, documentation, "");
        render_routine(
            output,
            name,
            symbol,
            documentation_row(unit, name, documentation),
            "",
            false,
        );
    }
}

fn render_routine(
    output: &mut String,
    name: &str,
    symbol: &IntrinsicStdSymbol,
    documentation: Option<&DocumentationRow>,
    indent: &str,
    is_static: bool,
) {
    let static_prefix = if is_static { "static " } else { "" };
    let declaration = if contains_error(&symbol.ty) || name.ends_with("AssertEquals") {
        polymorphic_declaration(name, documentation).unwrap_or_else(|| {
            fixed_declaration(
                name,
                &symbol.ty,
                symbol.kind == IntrinsicStdSymbolKind::Procedure,
            )
        })
    } else {
        fixed_declaration(
            name,
            &symbol.ty,
            symbol.kind == IntrinsicStdSymbolKind::Procedure,
        )
    };
    let _ = writeln!(output, "{indent}public {static_prefix}{declaration};");
    let _ = writeln!(output, "{indent}begin");
    let _ = writeln!(output, "{indent}  panic('Intrinsic API declaration');");
    let kind = if declaration.starts_with("procedure ") {
        "procedure"
    } else {
        "function"
    };
    let _ = writeln!(output, "{indent}end {kind};");
}

fn fixed_declaration(name: &str, ty: &Ty, force_procedure: bool) -> String {
    match ty {
        Ty::Function(function) if !force_procedure => format!(
            "function {name}({}): {}",
            parameters(&function.params),
            function.return_type
        ),
        Ty::Function(function) if force_procedure => {
            format!("procedure {name}({})", parameters(&function.params))
        }
        Ty::Procedure(procedure) => format!("procedure {name}({})", parameters(&procedure.params)),
        _ if force_procedure => format!("procedure {name}()"),
        _ => format!("function {name}(): integer"),
    }
}

fn contains_error(ty: &Ty) -> bool {
    match ty {
        Ty::Error => true,
        Ty::Applied(_, arguments) => arguments.iter().any(contains_error),
        Ty::Array(inner) | Ty::Channel(inner) | Ty::Option(inner) | Ty::Task(inner) => {
            contains_error(inner)
        }
        Ty::Result(ok, error) | Ty::Dict(ok, error) => contains_error(ok) || contains_error(error),
        Ty::Function(function) => {
            contains_error(&function.return_type)
                || function
                    .params
                    .iter()
                    .any(|parameter| contains_error(&parameter.ty))
        }
        Ty::Procedure(procedure) => procedure
            .params
            .iter()
            .any(|parameter| contains_error(&parameter.ty)),
        Ty::Record(_)
        | Ty::Enum(_)
        | Ty::Integer
        | Ty::Real
        | Ty::Boolean
        | Ty::String
        | Ty::Unit
        | Ty::Named(_)
        | Ty::GenericParam(_, _) => false,
    }
}

fn parameters(parameters: &[ParamTy]) -> String {
    parameters
        .iter()
        .map(|parameter| {
            let mutable = if parameter.mutable { "mutable " } else { "" };
            format!("{mutable}{}: {}", parameter.name, parameter.ty)
        })
        .collect::<Vec<_>>()
        .join("; ")
}

fn polymorphic_declaration(name: &str, documentation: Option<&DocumentationRow>) -> Option<String> {
    let row = documentation?;
    let signature = match name.rsplit('.').next().unwrap_or(name) {
        "Abs" => "Abs of (T)(N: T): T",
        "Min" => "Min of (T)(A: T; B: T): T",
        "Max" => "Max of (T)(A: T; B: T): T",
        "Sign" => "Sign of (T)(N: T): integer",
        "Clamp" => "Clamp of (T)(V: T; Lo: T; Hi: T): T",
        "AssertEquals" => "AssertEquals of (T)(Expected: T; Actual: T)",
        _ => &row.signature,
    };
    let kind = if row.kind == "procedure" {
        "procedure"
    } else {
        "function"
    };
    Some(format!("{kind} {signature}"))
}
