[package]
name = "fpas-program"
description = "Persistent executable program images for Functional Pascal"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fpas-binary = { path = "../fpas-binary" }
fpas-bytecode = { path = "../fpas-bytecode" }

[dev-dependencies]
allocation-counter = { workspace = true }
fpas-vm = { path = "../fpas-vm" }

[lints]
workspace = true
