//! Generates the `Std.Tui` command constants from the pinned Turbo Vision dependency.

use std::env;
use std::fs;
use std::io::{self, Write};
use std::path::Path;

use turbo_vision::core::command;

const UPSTREAM_COMMANDS: &[(&str, command::CommandId)] = &[
    ("CM_CONTINUE", command::CM_CONTINUE),
    ("CM_QUIT", command::CM_QUIT),
    ("CM_CLOSE", command::CM_CLOSE),
    ("CM_ZOOM", command::CM_ZOOM),
    ("CM_RESIZE", command::CM_RESIZE),
    ("CM_NEXT", command::CM_NEXT),
    ("CM_PREV", command::CM_PREV),
    ("CM_OK", command::CM_OK),
    ("CM_CANCEL", command::CM_CANCEL),
    ("CM_YES", command::CM_YES),
    ("CM_NO", command::CM_NO),
    ("CM_DEFAULT", command::CM_DEFAULT),
    ("CM_CUT", command::CM_CUT),
    ("CM_COPY", command::CM_COPY),
    ("CM_PASTE", command::CM_PASTE),
    ("CM_UNDO", command::CM_UNDO),
    ("CM_CLEAR", command::CM_CLEAR),
    ("CM_TILE", command::CM_TILE),
    ("CM_CASCADE", command::CM_CASCADE),
    ("CM_RECEIVED_FOCUS", command::CM_RECEIVED_FOCUS),
    ("CM_RELEASED_FOCUS", command::CM_RELEASED_FOCUS),
    ("CM_COMMAND_SET_CHANGED", command::CM_COMMAND_SET_CHANGED),
    ("CM_SELECT_WINDOW_NUM", command::CM_SELECT_WINDOW_NUM),
    ("CM_SCROLLBAR_CHANGED", command::CM_SCROLLBAR_CHANGED),
    ("CM_RECORD_HISTORY", command::CM_RECORD_HISTORY),
    ("CM_GRAB_DEFAULT", command::CM_GRAB_DEFAULT),
    ("CM_RELEASE_DEFAULT", command::CM_RELEASE_DEFAULT),
    ("CM_REDRAW", command::CM_REDRAW),
    ("CM_FOCUS_LINK", command::CM_FOCUS_LINK),
    ("CM_RADIO_SELECTED", command::CM_RADIO_SELECTED),
    ("CM_SHOW_HISTORY", command::CM_SHOW_HISTORY),
    ("CM_HISTORY_SELECTED", command::CM_HISTORY_SELECTED),
    ("CM_SCREENSHOT", command::CM_SCREENSHOT),
    ("CM_ABOUT", command::CM_ABOUT),
    ("CM_HELP_INDEX", command::CM_HELP_INDEX),
    ("CM_NEW", command::CM_NEW),
    ("CM_OPEN", command::CM_OPEN),
    ("CM_SAVE", command::CM_SAVE),
    ("CM_SAVE_AS", command::CM_SAVE_AS),
    ("CM_SAVE_ALL", command::CM_SAVE_ALL),
    ("CM_CLOSE_FILE", command::CM_CLOSE_FILE),
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    if let Err(error) = write_generated_constants() {
        eprintln!("failed to generate Std.Tui CM_* constants: {error}");
        std::process::exit(1);
    }
}

fn write_generated_constants() -> io::Result<()> {
    let out_dir = env::var_os("OUT_DIR")
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "Cargo did not set OUT_DIR"))?;
    let generated_path = Path::new(&out_dir).join("cm_constants_generated.rs");
    let mut generated = fs::File::create(generated_path)?;
    writeln!(
        generated,
        "// @generated by crates/fpas-std/build.rs; do not edit."
    )?;
    writeln!(generated)?;
    for &(name, value) in UPSTREAM_COMMANDS {
        writeln!(generated, "pub const {name}: i64 = {value};")?;
    }
    writeln!(generated)?;
    writeln!(
        generated,
        "/// Suggested base for application-private commands."
    )?;
    writeln!(generated, "pub const CM_USER: i64 = 4096;")
}
