use super::Intrinsic;

/// All intrinsic variants in a single array, used for round-trip testing.
#[cfg(test)]
const ALL_INTRINSICS: &[Intrinsic] = &[
    Intrinsic::ConsoleReadLn,
    Intrinsic::ConsoleRead,
    Intrinsic::ConsoleReadKey,
    Intrinsic::ConsoleKeyPressed,
    Intrinsic::ConsoleReadKeyEvent,
    Intrinsic::ConsoleClrScr,
    Intrinsic::ConsoleClrEol,
    Intrinsic::ConsoleGotoXY,
    Intrinsic::ConsoleWhereX,
    Intrinsic::ConsoleWhereY,
    Intrinsic::ConsoleWindMin,
    Intrinsic::ConsoleWindMax,
    Intrinsic::ConsoleWindow,
    Intrinsic::ConsoleTextColor,
    Intrinsic::ConsoleTextBackground,
    Intrinsic::ConsoleDelay,
    Intrinsic::ConsoleCursorOn,
    Intrinsic::ConsoleCursorOff,
    Intrinsic::ConsoleDelLine,
    Intrinsic::ConsoleInsLine,
    Intrinsic::ConsoleHighVideo,
    Intrinsic::ConsoleLowVideo,
    Intrinsic::ConsoleNormVideo,
    Intrinsic::ConsoleTextAttr,
    Intrinsic::ConsoleSetTextAttr,
    Intrinsic::ConsoleCursorBig,
    Intrinsic::ConsoleTextMode,
    Intrinsic::ConsoleLastMode,
    Intrinsic::ConsoleScreenWidth,
    Intrinsic::ConsoleScreenHeight,
    Intrinsic::ConsoleSound,
    Intrinsic::ConsoleNoSound,
    Intrinsic::ConsoleAssignCrt,
    Intrinsic::ConsoleEventPending,
    Intrinsic::ConsoleReadEvent,
    Intrinsic::ConsoleEnableRawMode,
    Intrinsic::ConsoleDisableRawMode,
    Intrinsic::ConsoleEnterAltScreen,
    Intrinsic::ConsoleLeaveAltScreen,
    Intrinsic::ConsoleEnableMouse,
    Intrinsic::ConsoleDisableMouse,
    Intrinsic::ConsoleEnableFocus,
    Intrinsic::ConsoleDisableFocus,
    Intrinsic::ConsoleEnablePaste,
    Intrinsic::ConsoleDisablePaste,
    Intrinsic::ConsoleReadEventTimeout,
    Intrinsic::ConsolePollEvent,
    Intrinsic::StrLength,
    Intrinsic::StrToUpper,
    Intrinsic::StrToLower,
    Intrinsic::StrTrim,
    Intrinsic::StrContains,
    Intrinsic::StrStartsWith,
    Intrinsic::StrEndsWith,
    Intrinsic::StrSubstring,
    Intrinsic::StrIndexOf,
    Intrinsic::StrReplace,
    Intrinsic::StrSplit,
    Intrinsic::StrJoin,
    Intrinsic::StrIsNumeric,
    Intrinsic::StrRepeat,
    Intrinsic::StrPadLeft,
    Intrinsic::StrPadRight,
    Intrinsic::StrPadCenter,
    Intrinsic::StrFromChar,
    Intrinsic::StrCharAt,
    Intrinsic::StrSetCharAt,
    Intrinsic::StrOrd,
    Intrinsic::StrChr,
    Intrinsic::StrInsert,
    Intrinsic::StrDelete,
    Intrinsic::StrReverse,
    Intrinsic::StrTrimLeft,
    Intrinsic::StrTrimRight,
    Intrinsic::StrLastIndexOf,
    Intrinsic::StrFormat,
    Intrinsic::ConvIntToStr,
    Intrinsic::ConvStrToInt,
    Intrinsic::ConvRealToStr,
    Intrinsic::ConvStrToReal,
    Intrinsic::ConvCharToStr,
    Intrinsic::ConvIntToReal,
    Intrinsic::ConvBoolToStr,
    Intrinsic::ConvStrToBool,
    Intrinsic::ConvIntToHex,
    Intrinsic::ConvHexToInt,
    Intrinsic::MathSqrt,
    Intrinsic::MathPow,
    Intrinsic::MathFloor,
    Intrinsic::MathCeil,
    Intrinsic::MathRound,
    Intrinsic::MathSin,
    Intrinsic::MathCos,
    Intrinsic::MathLog,
    Intrinsic::MathMin,
    Intrinsic::MathMax,
    Intrinsic::MathAbs,
    Intrinsic::MathTan,
    Intrinsic::MathArcSin,
    Intrinsic::MathArcCos,
    Intrinsic::MathArcTan,
    Intrinsic::MathArcTan2,
    Intrinsic::MathExp,
    Intrinsic::MathLog10,
    Intrinsic::MathLog2,
    Intrinsic::MathTrunc,
    Intrinsic::MathFrac,
    Intrinsic::MathSign,
    Intrinsic::MathClamp,
    Intrinsic::MathRandom,
    Intrinsic::MathRandomInt,
    Intrinsic::MathRandomize,
    Intrinsic::ArrayLength,
    Intrinsic::ArraySort,
    Intrinsic::ArrayReverse,
    Intrinsic::ArrayContains,
    Intrinsic::ArrayIndexOf,
    Intrinsic::ArraySlice,
    Intrinsic::ArrayMap,
    Intrinsic::ArrayFilter,
    Intrinsic::ArrayReduce,
    Intrinsic::ArrayConcat,
    Intrinsic::ArrayFill,
    Intrinsic::ArrayFind,
    Intrinsic::ArrayFindIndex,
    Intrinsic::ArrayAny,
    Intrinsic::ArrayAll,
    Intrinsic::ArrayFlatMap,
    Intrinsic::ArrayForEach,
    Intrinsic::ResultUnwrap,
    Intrinsic::ResultUnwrapOr,
    Intrinsic::ResultIsOk,
    Intrinsic::ResultIsError,
    Intrinsic::ResultMap,
    Intrinsic::ResultAndThen,
    Intrinsic::ResultOrElse,
    Intrinsic::OptionUnwrap,
    Intrinsic::OptionUnwrapOr,
    Intrinsic::OptionIsSome,
    Intrinsic::OptionIsNone,
    Intrinsic::OptionMap,
    Intrinsic::OptionAndThen,
    Intrinsic::OptionOrElse,
    Intrinsic::TaskWait,
    Intrinsic::TaskWaitAll,
    Intrinsic::DictLength,
    Intrinsic::DictContainsKey,
    Intrinsic::DictKeys,
    Intrinsic::DictValues,
    Intrinsic::DictRemove,
    Intrinsic::DictGet,
    Intrinsic::DictMerge,
    Intrinsic::DictMap,
    Intrinsic::DictFilter,
];

impl Intrinsic {
    pub fn from_u16(raw: u16) -> Option<Self> {
        Some(match raw {
            1 => Self::ConsoleReadLn,
            2 => Self::ConsoleRead,
            3 => Self::ConsoleReadKey,
            4 => Self::ConsoleKeyPressed,
            5 => Self::ConsoleReadKeyEvent,
            6 => Self::ConsoleClrScr,
            7 => Self::ConsoleClrEol,
            8 => Self::ConsoleGotoXY,
            9 => Self::ConsoleWhereX,
            10 => Self::ConsoleWhereY,
            11 => Self::ConsoleWindMin,
            12 => Self::ConsoleWindMax,
            13 => Self::ConsoleWindow,
            14 => Self::ConsoleTextColor,
            15 => Self::ConsoleTextBackground,
            16 => Self::ConsoleDelay,
            17 => Self::ConsoleCursorOn,
            18 => Self::ConsoleCursorOff,
            20 => Self::StrLength,
            21 => Self::StrToUpper,
            22 => Self::StrToLower,
            23 => Self::StrTrim,
            24 => Self::StrContains,
            25 => Self::StrStartsWith,
            26 => Self::StrEndsWith,
            27 => Self::StrSubstring,
            28 => Self::StrIndexOf,
            29 => Self::StrReplace,
            30 => Self::StrSplit,
            31 => Self::StrJoin,
            32 => Self::StrIsNumeric,
            40 => Self::ConvIntToStr,
            41 => Self::ConvStrToInt,
            42 => Self::ConvRealToStr,
            43 => Self::ConvStrToReal,
            44 => Self::ConvCharToStr,
            45 => Self::ConvIntToReal,
            60 => Self::MathSqrt,
            61 => Self::MathPow,
            62 => Self::MathFloor,
            63 => Self::MathCeil,
            64 => Self::MathRound,
            65 => Self::MathSin,
            66 => Self::MathCos,
            67 => Self::MathLog,
            68 => Self::MathMin,
            69 => Self::MathMax,
            70 => Self::MathAbs,
            80 => Self::ArrayLength,
            81 => Self::ArraySort,
            82 => Self::ArrayReverse,
            83 => Self::ArrayContains,
            84 => Self::ArrayIndexOf,
            85 => Self::ArraySlice,
            86 => Self::ArrayMap,
            87 => Self::ArrayFilter,
            88 => Self::ArrayReduce,
            90 => Self::ResultUnwrap,
            91 => Self::ResultUnwrapOr,
            92 => Self::ResultIsOk,
            93 => Self::ResultIsError,
            94 => Self::OptionUnwrap,
            95 => Self::OptionUnwrapOr,
            96 => Self::OptionIsSome,
            97 => Self::OptionIsNone,
            130 => Self::ResultMap,
            131 => Self::ResultAndThen,
            132 => Self::ResultOrElse,
            133 => Self::OptionMap,
            134 => Self::OptionAndThen,
            135 => Self::OptionOrElse,
            110 => Self::TaskWait,
            111 => Self::TaskWaitAll,
            120 => Self::DictLength,
            121 => Self::DictContainsKey,
            122 => Self::DictKeys,
            123 => Self::DictValues,
            124 => Self::DictRemove,
            125 => Self::DictGet,
            126 => Self::DictMerge,
            127 => Self::DictMap,
            128 => Self::DictFilter,
            170 => Self::ConsoleDelLine,
            171 => Self::ConsoleInsLine,
            172 => Self::ConsoleHighVideo,
            173 => Self::ConsoleLowVideo,
            174 => Self::ConsoleNormVideo,
            175 => Self::ConsoleTextAttr,
            176 => Self::ConsoleSetTextAttr,
            177 => Self::ConsoleCursorBig,
            178 => Self::ConsoleTextMode,
            179 => Self::ConsoleLastMode,
            180 => Self::ConsoleScreenWidth,
            181 => Self::ConsoleScreenHeight,
            182 => Self::ConsoleSound,
            183 => Self::ConsoleNoSound,
            184 => Self::ConsoleAssignCrt,
            185 => Self::ConsoleEventPending,
            186 => Self::ConsoleReadEvent,
            187 => Self::ConsoleEnableRawMode,
            188 => Self::ConsoleDisableRawMode,
            189 => Self::ConsoleEnterAltScreen,
            190 => Self::ConsoleLeaveAltScreen,
            191 => Self::ConsoleEnableMouse,
            192 => Self::ConsoleDisableMouse,
            193 => Self::ConsoleEnableFocus,
            194 => Self::ConsoleDisableFocus,
            195 => Self::ConsoleEnablePaste,
            196 => Self::ConsoleDisablePaste,
            197 => Self::ConsoleReadEventTimeout,
            198 => Self::ConsolePollEvent,
            200 => Self::StrRepeat,
            201 => Self::StrPadLeft,
            202 => Self::StrPadRight,
            203 => Self::StrPadCenter,
            204 => Self::StrFromChar,
            205 => Self::StrCharAt,
            206 => Self::StrSetCharAt,
            207 => Self::StrOrd,
            208 => Self::StrChr,
            209 => Self::StrInsert,
            210 => Self::StrDelete,
            211 => Self::StrReverse,
            212 => Self::StrTrimLeft,
            213 => Self::StrTrimRight,
            214 => Self::StrLastIndexOf,
            242 => Self::StrFormat,
            215 => Self::ConvBoolToStr,
            216 => Self::ConvStrToBool,
            217 => Self::ConvIntToHex,
            218 => Self::ConvHexToInt,
            219 => Self::MathTan,
            220 => Self::MathArcSin,
            221 => Self::MathArcCos,
            222 => Self::MathArcTan,
            223 => Self::MathArcTan2,
            224 => Self::MathExp,
            225 => Self::MathLog10,
            226 => Self::MathLog2,
            227 => Self::MathTrunc,
            228 => Self::MathFrac,
            229 => Self::MathSign,
            230 => Self::MathClamp,
            231 => Self::MathRandom,
            232 => Self::MathRandomInt,
            233 => Self::MathRandomize,
            234 => Self::ArrayConcat,
            235 => Self::ArrayFill,
            236 => Self::ArrayFind,
            237 => Self::ArrayFindIndex,
            238 => Self::ArrayAny,
            239 => Self::ArrayAll,
            240 => Self::ArrayFlatMap,
            241 => Self::ArrayForEach,
            _ => return None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn intrinsic_round_trip_encode_decode() {
        for &intr in ALL_INTRINSICS {
            let encoded: u16 = intr.into();
            let decoded = Intrinsic::from_u16(encoded);
            assert_eq!(
                decoded,
                Some(intr),
                "round-trip failed for {intr:?} (discriminant {encoded}): from_u16 returned {decoded:?}"
            );
        }
    }

    #[test]
    fn all_intrinsics_list_is_complete() {
        let count_in_list = ALL_INTRINSICS.len();
        // Probe the full u16 range to find any variant NOT in ALL_INTRINSICS.
        let mut found_via_probe = 0usize;
        for raw in 0..=u16::MAX {
            if Intrinsic::from_u16(raw).is_some() {
                found_via_probe += 1;
            }
        }
        assert_eq!(
            count_in_list, found_via_probe,
            "ALL_INTRINSICS has {count_in_list} entries but from_u16 recognises {found_via_probe} — \
             a variant was added to from_u16 or mod.rs without updating ALL_INTRINSICS"
        );
    }
}
