[package]
name = "fpas-fmt"
description = "Canonical source formatter for Functional Pascal"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fpas-parser = { path = "../fpas-parser" }
fpas-lexer = { path = "../fpas-lexer" }

[lints]
workspace = true
