use super::super::super::compile_ok;
use fpas_bytecode::intrinsic::GraphIntrinsic;
use fpas_bytecode::{Intrinsic, Op};

#[test]
fn std_graph_phase1_calls_lower_to_graph_intrinsics() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(640, 480, 'Graph smoke');
  var Screen: Size := Application.Size(App);
  Application.RequestRedraw(App);
    Application.Clear(App, $00010203);
    Application.PutPixel(App, 1, 0, $00ABCDEF);
    Application.DrawLine(App, 0, 0, 3, 3, $00000010);
    Application.DrawRect(App, 1, 1, 2, 2, $00000020);
    Application.FillRect(App, 0, 0, 1, 1, $00000030);
    Application.DrawCircle(App, 3, 3, 1, $00000040);
        Application.DrawText(App, 0, 0, 'A', $00000050);
    Application.Present(App);
  var Pixels: array of integer := [$00102040, $00102040];
  Application.UploadFrame(App, 1, 2, Pixels);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationOpen))
        )),
        "expected Application.Open intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationSize))
        )),
        "expected Application.Size intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationRequestRedraw))
        )),
        "expected Application.RequestRedraw intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationUploadFrame))
        )),
        "expected Application.UploadFrame intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationClose))
        )),
        "expected Application.Close intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationClear))
        )),
        "expected Application.Clear intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationPutPixel))
        )),
        "expected Application.PutPixel intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationPresent))
        )),
        "expected Application.Present intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawLine))
        )),
        "expected Application.DrawLine intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawRect))
        )),
        "expected Application.DrawRect intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationFillRect))
        )),
        "expected Application.FillRect intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawCircle))
        )),
        "expected Application.DrawCircle intrinsic in generated bytecode"
    );
    assert!(
        chunk.code().iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawText))
        )),
        "expected Application.DrawText intrinsic in generated bytecode"
    );
}
