//! Generates editor-only FPAS declarations for intrinsic `Std.*` units.

#[path = "export_intrinsic_std_api/documentation.rs"]
mod documentation;

use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use documentation::{
    default_value, documentation_row, parameter_description, render_documentation,
};
use fpas_sema::{
    IntrinsicStdSymbol, IntrinsicStdSymbolKind, ParamTy, Ty, intrinsic_std_symbols,
    intrinsic_std_units,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let repository = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .ok_or("fpas-sema must live below the repository root")?;
    let documentation = documentation_rows(&repository.join("docs/pascal/std"))?;
    if !documentation.contains_key(&(String::from("Std.Array"), String::from("all"))) {
        return Err("Std.Array.All documentation row is missing".into());
    }
    let output = repository.join("lib/api/Std");
    fs::create_dir_all(&output)?;

    for unit in intrinsic_std_units() {
        let path = output.join(format!("{}.fpas", unit.trim_start_matches("Std.")));
        let source = render_unit(unit, &intrinsic_std_symbols(unit), &documentation)
            .map_err(io::Error::other)?;
        let (parsed, diagnostics) = fpas_parser::parse_compilation_unit(&source);
        if !diagnostics.is_empty() {
            return Err(format!("generated {} is invalid: {diagnostics:?}", path.display()).into());
        }
        let source = fpas_fmt::format_source(&source, &parsed)?;
        fs::write(path, source)?;
    }
    Ok(())
}

#[derive(Debug, Clone)]
struct DocumentationRow {
    kind: String,
    signature: String,
    summary: String,
}

fn documentation_rows(root: &Path) -> io::Result<HashMap<(String, String), DocumentationRow>> {
    let mut paths = Vec::new();
    markdown_files(root, &mut paths)?;
    let known_units = intrinsic_std_units();
    let mut rows = HashMap::new();
    for path in paths {
        let source = fs::read_to_string(path)?;
        let heading = source.lines().find(|line| line.starts_with("# "));
        let Some(unit) = known_units
            .iter()
            .find(|unit| heading.is_some_and(|line| line.contains(**unit)))
        else {
            continue;
        };
        for line in source.lines().filter(|line| line.starts_with('|')) {
            let columns = line.split('|').map(str::trim).collect::<Vec<_>>();
            let Some(kind) = columns.get(1).copied() else {
                continue;
            };
            if !matches!(kind, "const" | "function" | "procedure" | "type") {
                continue;
            }
            let Some(signature) = columns.get(2).and_then(|value| inline_code(value)) else {
                continue;
            };
            let name = signature
                .split(['(', ':'])
                .next()
                .unwrap_or(signature)
                .trim()
                .to_ascii_lowercase();
            rows.entry(((*unit).to_owned(), name))
                .or_insert_with(|| DocumentationRow {
                    kind: kind.to_owned(),
                    signature: signature.to_owned(),
                    summary: columns.get(3).copied().unwrap_or_default().to_owned(),
                });
        }
    }
    Ok(rows)
}

fn markdown_files(directory: &Path, output: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            markdown_files(&path, output)?;
        } else if path.extension().is_some_and(|extension| extension == "md") {
            output.push(path);
        }
    }
    Ok(())
}

fn inline_code(value: &str) -> Option<&str> {
    let start = value.find('`')? + 1;
    let end = value.get(start..)?.find('`')? + start;
    value.get(start..end)
}

fn render_unit(
    unit: &str,
    symbols: &[IntrinsicStdSymbol],
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<String, String> {
    let mut output = format!(
        "unit {unit};\n\n// Generated by `cargo run -p fpas-sema --example export_intrinsic_std_api`.\n// Edit the Rust registry and `docs/pascal/std/`, then regenerate this editor declaration surface.\n// Runtime behavior is implemented by the compiler, VM, or Rust standard-library crate.\n"
    );
    let prefix = format!("{unit}.");
    let mut by_name = symbols
        .iter()
        .map(|symbol| {
            (
                symbol.qualified_name.trim_start_matches(&prefix).to_owned(),
                symbol,
            )
        })
        .collect::<BTreeMap<_, _>>();

    render_constants(&mut output, unit, &mut by_name, documentation)?;
    render_types(&mut output, unit, &mut by_name, documentation)?;
    render_routines(&mut output, unit, &by_name, documentation);
    Ok(output)
}

fn render_constants(
    output: &mut String,
    unit: &str,
    symbols: &mut BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<(), String> {
    let names = symbols
        .iter()
        .filter(|(_, symbol)| symbol.kind == IntrinsicStdSymbolKind::Constant)
        .map(|(name, _)| name.clone())
        .collect::<Vec<_>>();
    if names.is_empty() {
        return Ok(());
    }
    output.push_str("\npublic const\n");
    for name in names {
        let symbol = take_symbol(symbols, &name, "constant")?;
        render_documentation(output, unit, &name, symbol, documentation, "  ");
        let _ = writeln!(
            output,
            "  {name}: {} := {};",
            symbol.ty,
            default_value(&symbol.ty)
        );
    }
    Ok(())
}

fn render_types(
    output: &mut String,
    unit: &str,
    symbols: &mut BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<(), String> {
    let type_names = symbols
        .iter()
        .filter(|(name, symbol)| symbol.kind == IntrinsicStdSymbolKind::Type && !name.contains('.'))
        .map(|(name, _)| name.clone())
        .collect::<Vec<_>>();
    if type_names.is_empty() {
        return Ok(());
    }
    output.push_str("\npublic type\n");
    for name in type_names {
        let symbol = take_symbol(symbols, &name, "type")?;
        render_documentation(output, unit, &name, symbol, documentation, "  ");
        match &symbol.ty {
            Ty::Enum(value) => render_enum(output, unit, &name, value),
            Ty::Record(value) => {
                let member_names = symbols
                    .keys()
                    .filter(|candidate| candidate.starts_with(&format!("{name}.")))
                    .cloned()
                    .collect::<Vec<_>>();
                render_record(
                    output,
                    unit,
                    &name,
                    value,
                    &member_names,
                    symbols,
                    documentation,
                )?;
            }
            _ => {
                let _ = writeln!(output, "  {name} = {};", symbol.ty);
            }
        }
    }
    Ok(())
}

fn render_enum(output: &mut String, _unit: &str, name: &str, value: &fpas_sema::EnumTy) {
    let _ = writeln!(output, "  {name} = enum");
    for variant in &value.variants {
        let _ = writeln!(output, "    // `{}` enum member.", variant.name);
        if !variant.fields.is_empty() {
            output.push_str("    //\n    // Parameters:\n");
            for (field, ty) in &variant.fields {
                let _ = writeln!(
                    output,
                    "    // - `{field}`: {}",
                    parameter_description(
                        field,
                        &format!("{name}.{}", variant.name),
                        Some(&ty.to_string())
                    )
                );
            }
        }
        if !is_source_identifier(&variant.name) {
            continue;
        }
        let separator = ";";
        if variant.fields.is_empty() {
            let _ = writeln!(output, "    {}{separator}", variant.name);
        } else {
            let fields = variant
                .fields
                .iter()
                .map(|(field, ty)| format!("{field}: {ty}"))
                .collect::<Vec<_>>()
                .join("; ");
            let _ = writeln!(output, "    {}({fields}){separator}", variant.name);
        }
    }
    output.push_str("  end;\n");
}

fn is_source_identifier(name: &str) -> bool {
    fpas_lexer::lex(name)
        .0
        .first()
        .is_some_and(|token| matches!(token.token, fpas_lexer::Token::Ident(_)))
}

fn render_record(
    output: &mut String,
    unit: &str,
    name: &str,
    value: &fpas_sema::RecordTy,
    member_names: &[String],
    symbols: &mut BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) -> Result<(), String> {
    let _ = writeln!(output, "  {name} = record");
    if value.fields.is_empty() && member_names.is_empty() {
        output.push_str("    // Compiler-owned storage for this opaque handle.\n");
        output.push_str("    _IntrinsicHandle: integer;\n");
    } else {
        for (field, ty) in &value.fields {
            let _ = writeln!(output, "    public {field}: {ty};");
        }
    }
    for member_name in member_names {
        let symbol = take_symbol(symbols, member_name, "record member")?;
        if symbol.kind == IntrinsicStdSymbolKind::EnumMember {
            continue;
        }
        let short_name = member_name.rsplit('.').next().unwrap_or(member_name);
        render_documentation(output, unit, member_name, symbol, documentation, "    ");
        render_routine(
            output,
            short_name,
            symbol,
            documentation_row(unit, member_name, documentation),
            "    ",
            true,
        );
    }
    output.push_str("  end;\n");
    Ok(())
}

fn take_symbol<'a>(
    symbols: &mut BTreeMap<String, &'a IntrinsicStdSymbol>,
    name: &str,
    kind: &str,
) -> Result<&'a IntrinsicStdSymbol, String> {
    symbols
        .remove(name)
        .ok_or_else(|| format!("catalog {kind} `{name}` is missing"))
}

fn render_routines(
    output: &mut String,
    unit: &str,
    symbols: &BTreeMap<String, &IntrinsicStdSymbol>,
    documentation: &HashMap<(String, String), DocumentationRow>,
) {
    for (name, symbol) in symbols {
        if !matches!(
            symbol.kind,
            IntrinsicStdSymbolKind::Function | IntrinsicStdSymbolKind::Procedure
        ) || name.contains('.')
        {
            continue;
        }
        output.push('\n');
        render_documentation(output, unit, name, symbol, documentation, "");
        render_routine(
            output,
            name,
            symbol,
            documentation_row(unit, name, documentation),
            "",
            false,
        );
    }
}

fn render_routine(
    output: &mut String,
    name: &str,
    symbol: &IntrinsicStdSymbol,
    documentation: Option<&DocumentationRow>,
    indent: &str,
    is_static: bool,
) {
    let static_prefix = if is_static { "static " } else { "" };
    let declaration = if contains_error(&symbol.ty) || name.ends_with("AssertEquals") {
        polymorphic_declaration(name, documentation).unwrap_or_else(|| {
            fixed_declaration(
                name,
                &symbol.ty,
                symbol.kind == IntrinsicStdSymbolKind::Procedure,
            )
        })
    } else {
        fixed_declaration(
            name,
            &symbol.ty,
            symbol.kind == IntrinsicStdSymbolKind::Procedure,
        )
    };
    let _ = writeln!(output, "{indent}public {static_prefix}{declaration};");
    let _ = writeln!(output, "{indent}begin");
    let _ = writeln!(output, "{indent}  panic('Intrinsic API declaration')");
    let _ = writeln!(output, "{indent}end;");
}

fn fixed_declaration(name: &str, ty: &Ty, force_procedure: bool) -> String {
    match ty {
        Ty::Function(function) if !force_procedure => format!(
            "function {name}({}): {}",
            parameters(&function.params),
            function.return_type
        ),
        Ty::Function(function) if force_procedure => {
            format!("procedure {name}({})", parameters(&function.params))
        }
        Ty::Procedure(procedure) => format!("procedure {name}({})", parameters(&procedure.params)),
        _ if force_procedure => format!("procedure {name}()"),
        _ => format!("function {name}(): integer"),
    }
}

fn contains_error(ty: &Ty) -> bool {
    match ty {
        Ty::Error => true,
        Ty::Array(inner) | Ty::Option(inner) | Ty::Task(inner) => contains_error(inner),
        Ty::Result(ok, error) | Ty::Dict(ok, error) => contains_error(ok) || contains_error(error),
        Ty::Function(function) => {
            contains_error(&function.return_type)
                || function
                    .params
                    .iter()
                    .any(|parameter| contains_error(&parameter.ty))
        }
        Ty::Procedure(procedure) => procedure
            .params
            .iter()
            .any(|parameter| contains_error(&parameter.ty)),
        Ty::Record(_)
        | Ty::Enum(_)
        | Ty::Integer
        | Ty::Real
        | Ty::Boolean
        | Ty::String
        | Ty::Unit
        | Ty::Named(_)
        | Ty::GenericParam(_, _) => false,
    }
}

fn parameters(parameters: &[ParamTy]) -> String {
    parameters
        .iter()
        .map(|parameter| {
            let mutable = if parameter.mutable { "mutable " } else { "" };
            format!("{mutable}{}: {}", parameter.name, parameter.ty)
        })
        .collect::<Vec<_>>()
        .join("; ")
}

fn polymorphic_declaration(name: &str, documentation: Option<&DocumentationRow>) -> Option<String> {
    let row = documentation?;
    let signature = match name.rsplit('.').next().unwrap_or(name) {
        "Abs" => "Abs<T>(N: T): T",
        "Min" => "Min<T>(A: T; B: T): T",
        "Max" => "Max<T>(A: T; B: T): T",
        "Sign" => "Sign<T>(N: T): integer",
        "Clamp" => "Clamp<T>(V: T; Lo: T; Hi: T): T",
        "AssertEquals" => "AssertEquals<T>(Expected: T; Actual: T)",
        _ => &row.signature,
    };
    let kind = if row.kind == "procedure" {
        "procedure"
    } else {
        "function"
    };
    Some(format!("{kind} {signature}"))
}
