use super::std_symbols;

pub(in super::super) const STD_CONSOLE_SYMBOLS: &[&str] = &[
    std_symbols::STD_CONSOLE_WRITE_LN,
    std_symbols::STD_CONSOLE_WRITE,
    std_symbols::STD_CONSOLE_CLR_SCR,
    std_symbols::STD_CONSOLE_CLR_EOL,
    std_symbols::STD_CONSOLE_GOTO_XY,
    std_symbols::STD_CONSOLE_WHERE_X,
    std_symbols::STD_CONSOLE_WHERE_Y,
    std_symbols::STD_CONSOLE_WIND_MIN,
    std_symbols::STD_CONSOLE_WIND_MAX,
    std_symbols::STD_CONSOLE_DEL_LINE,
    std_symbols::STD_CONSOLE_INS_LINE,
    std_symbols::STD_CONSOLE_WINDOW,
    std_symbols::STD_CONSOLE_TEXT_COLOR,
    std_symbols::STD_CONSOLE_TEXT_BACKGROUND,
    std_symbols::STD_CONSOLE_HIGH_VIDEO,
    std_symbols::STD_CONSOLE_LOW_VIDEO,
    std_symbols::STD_CONSOLE_NORM_VIDEO,
    std_symbols::STD_CONSOLE_TEXT_ATTR,
    std_symbols::STD_CONSOLE_SET_TEXT_ATTR,
    std_symbols::STD_CONSOLE_DELAY,
    std_symbols::STD_CONSOLE_CURSOR_ON,
    std_symbols::STD_CONSOLE_CURSOR_OFF,
    std_symbols::STD_CONSOLE_CURSOR_BIG,
    std_symbols::STD_CONSOLE_TEXT_MODE,
    std_symbols::STD_CONSOLE_LAST_MODE,
    std_symbols::STD_CONSOLE_SCREEN_WIDTH,
    std_symbols::STD_CONSOLE_SCREEN_HEIGHT,
    std_symbols::STD_CONSOLE_SOUND,
    std_symbols::STD_CONSOLE_NO_SOUND,
    std_symbols::STD_CONSOLE_ASSIGN_CRT,
    std_symbols::STD_CONSOLE_READ_LN,
    std_symbols::STD_CONSOLE_READ,
    std_symbols::STD_CONSOLE_READ_KEY,
    std_symbols::STD_CONSOLE_KEY_PRESSED,
    std_symbols::STD_CONSOLE_READ_KEY_EVENT,
    std_symbols::STD_CONSOLE_EVENT_PENDING,
    std_symbols::STD_CONSOLE_READ_EVENT,
    std_symbols::STD_CONSOLE_KEY_EVENT,
    std_symbols::STD_CONSOLE_KEY_KIND,
    std_symbols::STD_CONSOLE_EVENT,
    std_symbols::STD_CONSOLE_EVENT_KIND,
    std_symbols::STD_CONSOLE_MOUSE_ACTION,
    std_symbols::STD_CONSOLE_MOUSE_BUTTON,
    std_symbols::STD_CONSOLE_ENABLE_RAW_MODE,
    std_symbols::STD_CONSOLE_DISABLE_RAW_MODE,
    std_symbols::STD_CONSOLE_ENTER_ALT_SCREEN,
    std_symbols::STD_CONSOLE_LEAVE_ALT_SCREEN,
    std_symbols::STD_CONSOLE_ENABLE_MOUSE,
    std_symbols::STD_CONSOLE_DISABLE_MOUSE,
    std_symbols::STD_CONSOLE_ENABLE_FOCUS,
    std_symbols::STD_CONSOLE_DISABLE_FOCUS,
    std_symbols::STD_CONSOLE_ENABLE_PASTE,
    std_symbols::STD_CONSOLE_DISABLE_PASTE,
    std_symbols::STD_CONSOLE_BLACK,
    std_symbols::STD_CONSOLE_BLUE,
    std_symbols::STD_CONSOLE_GREEN,
    std_symbols::STD_CONSOLE_CYAN,
    std_symbols::STD_CONSOLE_RED,
    std_symbols::STD_CONSOLE_MAGENTA,
    std_symbols::STD_CONSOLE_BROWN,
    std_symbols::STD_CONSOLE_LIGHT_GRAY,
    std_symbols::STD_CONSOLE_DARK_GRAY,
    std_symbols::STD_CONSOLE_LIGHT_BLUE,
    std_symbols::STD_CONSOLE_LIGHT_GREEN,
    std_symbols::STD_CONSOLE_LIGHT_CYAN,
    std_symbols::STD_CONSOLE_LIGHT_RED,
    std_symbols::STD_CONSOLE_LIGHT_MAGENTA,
    std_symbols::STD_CONSOLE_YELLOW,
    std_symbols::STD_CONSOLE_WHITE,
    std_symbols::STD_CONSOLE_BLINK,
    std_symbols::STD_CONSOLE_BW40,
    std_symbols::STD_CONSOLE_C40,
    std_symbols::STD_CONSOLE_BW80,
    std_symbols::STD_CONSOLE_C80,
    std_symbols::STD_CONSOLE_CO40,
    std_symbols::STD_CONSOLE_CO80,
    std_symbols::STD_CONSOLE_MONO,
    std_symbols::STD_CONSOLE_FONT_8X8,
];

pub(in super::super) const STD_STR_SYMBOLS: &[&str] = &[
    std_symbols::STD_STR_LENGTH,
    std_symbols::STD_STR_TO_UPPER,
    std_symbols::STD_STR_TO_LOWER,
    std_symbols::STD_STR_TRIM,
    std_symbols::STD_STR_CONTAINS,
    std_symbols::STD_STR_STARTS_WITH,
    std_symbols::STD_STR_ENDS_WITH,
    std_symbols::STD_STR_SUBSTRING,
    std_symbols::STD_STR_INDEX_OF,
    std_symbols::STD_STR_REPLACE,
    std_symbols::STD_STR_SPLIT,
    std_symbols::STD_STR_JOIN,
    std_symbols::STD_STR_IS_NUMERIC,
];

pub(in super::super) const STD_CONV_SYMBOLS: &[&str] = &[
    std_symbols::STD_CONV_INT_TO_STR,
    std_symbols::STD_CONV_STR_TO_INT,
    std_symbols::STD_CONV_REAL_TO_STR,
    std_symbols::STD_CONV_STR_TO_REAL,
    std_symbols::STD_CONV_CHAR_TO_STR,
    std_symbols::STD_CONV_INT_TO_REAL,
];

pub(in super::super) const STD_MATH_SYMBOLS: &[&str] = &[
    std_symbols::STD_MATH_PI,
    std_symbols::STD_MATH_SQRT,
    std_symbols::STD_MATH_POW,
    std_symbols::STD_MATH_FLOOR,
    std_symbols::STD_MATH_CEIL,
    std_symbols::STD_MATH_ROUND,
    std_symbols::STD_MATH_SIN,
    std_symbols::STD_MATH_COS,
    std_symbols::STD_MATH_LOG,
    std_symbols::STD_MATH_ABS,
    std_symbols::STD_MATH_MIN,
    std_symbols::STD_MATH_MAX,
];

pub(in super::super) const STD_ARRAY_SYMBOLS: &[&str] = &[
    std_symbols::STD_ARRAY_LENGTH,
    std_symbols::STD_ARRAY_SORT,
    std_symbols::STD_ARRAY_REVERSE,
    std_symbols::STD_ARRAY_CONTAINS,
    std_symbols::STD_ARRAY_INDEX_OF,
    std_symbols::STD_ARRAY_SLICE,
    std_symbols::STD_ARRAY_PUSH,
    std_symbols::STD_ARRAY_POP,
    std_symbols::STD_ARRAY_MAP,
    std_symbols::STD_ARRAY_FILTER,
    std_symbols::STD_ARRAY_REDUCE,
];

pub(in super::super) const STD_RESULT_SYMBOLS: &[&str] = &[
    std_symbols::STD_RESULT_UNWRAP,
    std_symbols::STD_RESULT_UNWRAP_OR,
    std_symbols::STD_RESULT_IS_OK,
    std_symbols::STD_RESULT_IS_ERR,
];

pub(in super::super) const STD_OPTION_SYMBOLS: &[&str] = &[
    std_symbols::STD_OPTION_UNWRAP,
    std_symbols::STD_OPTION_UNWRAP_OR,
    std_symbols::STD_OPTION_IS_SOME,
    std_symbols::STD_OPTION_IS_NONE,
];

pub(in super::super) const STD_CHANNEL_SYMBOLS: &[&str] = &[
    std_symbols::STD_CHANNEL_MAKE,
    std_symbols::STD_CHANNEL_MAKE_BUFFERED,
    std_symbols::STD_CHANNEL_SEND,
    std_symbols::STD_CHANNEL_RECEIVE,
    std_symbols::STD_CHANNEL_TRY_RECEIVE,
    std_symbols::STD_CHANNEL_CLOSE,
];

pub(in super::super) const STD_TASK_SYMBOLS: &[&str] =
    &[std_symbols::STD_TASK_WAIT, std_symbols::STD_TASK_WAIT_ALL];

pub(in super::super) const STD_DICT_SYMBOLS: &[&str] = &[
    std_symbols::STD_DICT_LENGTH,
    std_symbols::STD_DICT_CONTAINS_KEY,
    std_symbols::STD_DICT_KEYS,
    std_symbols::STD_DICT_VALUES,
    std_symbols::STD_DICT_REMOVE,
];
