//! Std.* symbol name constants and per-unit registry groups.

pub mod std_symbols;

pub(super) use std_symbols::{
    STD_ARGS_SYMBOLS, STD_ARRAY_SYMBOLS, STD_CONSOLE_SYMBOLS, STD_CONV_SYMBOLS, STD_DICT_SYMBOLS,
    STD_ENV_SYMBOLS, STD_FS_SYMBOLS, STD_GRAPH_SYMBOLS, STD_JSON_SYMBOLS, STD_MATH_SYMBOLS,
    STD_OPTION_SYMBOLS, STD_PARSE_SYMBOLS, STD_PATH_SYMBOLS, STD_PROC_SYMBOLS, STD_RANDOM_SYMBOLS,
    STD_RESULT_SYMBOLS, STD_STR_SYMBOLS, STD_TASK_SYMBOLS, STD_TEST_SYMBOLS, STD_TIME_SYMBOLS,
    STD_TOML_SYMBOLS,
};
