//! Audited pure intrinsic signatures; new symbols require an explicit classification.
//!
//! **Documentation:** `docs/pascal/std/README.md`.

use super::std_symbols as s;

/// Whether an intrinsic function has an explicit purity guarantee.
///
/// Collection callbacks and all concrete parameter/result components must satisfy
/// the same data capability as source pure functions. Caller mutation, resource
/// state, clocks, randomness, and action traversal have no purity guarantee.
pub fn intrinsic_std_function_is_pure(name: &str) -> bool {
    PURE_FUNCTIONS
        .iter()
        .any(|candidate| name.eq_ignore_ascii_case(candidate))
}

const PURE_FUNCTIONS: &[&str] = &[
    s::STD_MATH_SQRT,
    s::STD_MATH_POW,
    s::STD_MATH_FLOOR,
    s::STD_MATH_CEIL,
    s::STD_MATH_ROUND,
    s::STD_MATH_SIN,
    s::STD_MATH_COS,
    s::STD_MATH_LOG,
    s::STD_MATH_ABS,
    s::STD_MATH_MIN,
    s::STD_MATH_MAX,
    s::STD_MATH_TAN,
    s::STD_MATH_ARC_SIN,
    s::STD_MATH_ARC_COS,
    s::STD_MATH_ARC_TAN,
    s::STD_MATH_EXP,
    s::STD_MATH_TRUNC,
    s::STD_MATH_FRAC,
    s::STD_MATH_SIGN,
    s::STD_MATH_CLAMP,
    s::STD_BITS_BIT_AND,
    s::STD_BITS_BIT_OR,
    s::STD_BITS_BIT_XOR,
    s::STD_BITS_BIT_NOT,
    s::STD_BITS_SHIFT_LEFT,
    s::STD_BITS_SHIFT_RIGHT,
    s::STD_STR_LENGTH,
    s::STD_STR_TO_UPPER,
    s::STD_STR_TO_LOWER,
    s::STD_STR_TRIM,
    s::STD_STR_CONTAINS,
    s::STD_STR_STARTS_WITH,
    s::STD_STR_ENDS_WITH,
    s::STD_STR_SUBSTRING,
    s::STD_STR_INDEX_OF,
    s::STD_STR_REPLACE,
    s::STD_STR_SPLIT,
    s::STD_STR_JOIN,
    s::STD_STR_IS_NUMERIC,
    s::STD_STR_REPEAT,
    s::STD_STR_PAD_LEFT,
    s::STD_STR_PAD_RIGHT,
    s::STD_STR_PAD_CENTER,
    s::STD_STR_FROM_CHAR,
    s::STD_STR_CHAR_AT,
    s::STD_STR_SET_CHAR_AT,
    s::STD_STR_ORD,
    s::STD_STR_CHR,
    s::STD_STR_INSERT,
    s::STD_STR_DELETE,
    s::STD_STR_REVERSE,
    s::STD_STR_TRIM_LEFT,
    s::STD_STR_TRIM_RIGHT,
    s::STD_STR_LAST_INDEX_OF,
    s::STD_STR_FORMAT,
    s::STD_STR_MAP,
    s::STD_STR_FILTER,
    s::STD_STR_REDUCE,
    s::STD_CONV_INT_TO_STR,
    s::STD_CONV_STR_TO_INT,
    s::STD_CONV_REAL_TO_STR,
    s::STD_CONV_STR_TO_REAL,
    s::STD_CONV_INT_TO_REAL,
    s::STD_CONV_BOOL_TO_STR,
    s::STD_CONV_STR_TO_BOOL,
    s::STD_CONV_INT_TO_HEX,
    s::STD_CONV_HEX_TO_INT,
    s::STD_PARSE_TRY_INT,
    s::STD_PARSE_TRY_REAL,
    s::STD_PARSE_TRY_BOOL,
    s::STD_PATH_JOIN,
    s::STD_PATH_BASE_NAME,
    s::STD_PATH_DIR_NAME,
    s::STD_PATH_EXTENSION,
    s::STD_PATH_NORMALIZE,
    s::STD_ARRAY_LENGTH,
    s::STD_ARRAY_SORT,
    s::STD_ARRAY_REVERSE,
    s::STD_ARRAY_CONTAINS,
    s::STD_ARRAY_INDEX_OF,
    s::STD_ARRAY_SLICE,
    s::STD_ARRAY_MAP,
    s::STD_ARRAY_FILTER,
    s::STD_ARRAY_REDUCE,
    s::STD_ARRAY_CONCAT,
    s::STD_ARRAY_FILL,
    s::STD_ARRAY_FIND,
    s::STD_ARRAY_FIND_INDEX,
    s::STD_ARRAY_ANY,
    s::STD_ARRAY_ALL,
    s::STD_ARRAY_FLAT_MAP,
    s::STD_DICT_LENGTH,
    s::STD_DICT_CONTAINS_KEY,
    s::STD_DICT_KEYS,
    s::STD_DICT_VALUES,
    s::STD_DICT_REMOVE,
    s::STD_DICT_GET,
    s::STD_DICT_MERGE,
    s::STD_DICT_MAP,
    s::STD_DICT_FILTER,
    s::STD_DICT_REDUCE,
    s::STD_OPTION_UNWRAP,
    s::STD_OPTION_UNWRAP_OR,
    s::STD_OPTION_IS_SOME,
    s::STD_OPTION_IS_NONE,
    s::STD_OPTION_MAP,
    s::STD_OPTION_AND_THEN,
    s::STD_OPTION_OR_ELSE,
    s::STD_RESULT_UNWRAP,
    s::STD_RESULT_UNWRAP_OR,
    s::STD_RESULT_IS_OK,
    s::STD_RESULT_IS_ERR,
    s::STD_RESULT_MAP,
    s::STD_RESULT_AND_THEN,
    s::STD_RESULT_OR_ELSE,
    s::STD_JSON_PARSE,
    s::STD_JSON_STRINGIFY,
    s::STD_TOML_PARSE,
    s::STD_TOML_STRINGIFY,
];
