//! Compiler integration tests for `Std.Graph` lowering.
//!
//! **Documentation:** `docs/future/std.graph/02-pascal-surface.md`, `docs/future/std.graph/04-implementation-plan.md` (from the repository root).

use super::super::{compile_and_run, compile_err, compile_ok};
use fpas_bytecode::intrinsic::GraphIntrinsic;
use fpas_bytecode::{Intrinsic, Op};

#[test]
fn std_graph_phase1_calls_lower_to_graph_intrinsics() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(640, 480, 'Graph smoke');
  var Screen: Size := Application.Size(App);
  var Pending: Option of Event := Application.PollEvent(App);
  var Pixels: array of integer := [$00102040, $00102040];
  Application.UploadFrame(App, 1, 2, Pixels);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationOpen))
        )),
        "expected Application.Open intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationSize))
        )),
        "expected Application.Size intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationPollEvent))
        )),
        "expected Application.PollEvent intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationUploadFrame))
        )),
        "expected Application.UploadFrame intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationClose))
        )),
        "expected Application.Close intrinsic in generated bytecode"
    );
}

#[test]
fn std_graph_open_rejects_wrong_argument_count_during_compilation() {
    let err = compile_err(
        "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(640, 480)
end.",
    );

    assert!(
        err.message.contains("expects 3 arguments"),
        "unexpected compiler error: {}",
        err.message
    );
}

#[test]
fn std_graph_phase1_runtime_bridge_supports_size_poll_upload_and_close() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Graph, Std.Option;

begin
    var App: Application := Application.Open(2, 2, 'Graph smoke');
  var Screen: Size := Application.Size(App);
  Std.Console.WriteLn(Screen.width);
  Std.Console.WriteLn(Screen.height);
  Std.Console.WriteLn(Std.Option.IsNone(Application.PollEvent(App)));
  var Pixels: array of integer := [$00102040, $00010203, $00000000, $00FFFFFF];
  Application.UploadFrame(App, 2, 2, Pixels);
  Application.Close(App)
end.",
    );

    assert_eq!(out.lines, vec!["2", "2", "true"]);
}