//! Compiler integration tests for `Std.Graph` lowering.
//!
//! **Documentation:** `docs/pascal/std/graph.md` (from the repository root).

use super::super::{compile_and_run, compile_err, compile_ok, compile_run_error};
use fpas_bytecode::intrinsic::GraphIntrinsic;
use fpas_bytecode::{Intrinsic, Op};
use fpas_std::{
    ConsoleKeyEvent, GraphEvent, key_event::key_kind_index, last_headless_graph_frame_for_tests,
    with_headless_graph_backend_for_tests,
};

const GRAPH_BASICS_EXAMPLE: &str =
    include_str!("../../../../../examples/pascal/std/graph_basics.fpas");
const JULIA_GRAPH_EXAMPLE: &str =
    include_str!("../../../../../examples/math/julia/julia_graph.fpas");
const MANDELBROT_GRAPH_EXAMPLE: &str =
    include_str!("../../../../../examples/math/mandelbrot/mandelbrot_graph.fpas");

fn with_headless<T>(f: impl FnOnce() -> T) -> T {
    with_headless_graph_backend_for_tests(f)
}

fn compile_run_with_graph_events(source: &str, events: &[GraphEvent]) -> fpas_vm::VmOutput {
    let chunk = compile_ok(source);
    let mut vm = fpas_vm::Vm::new(chunk);
    for event in events {
        vm.push_graph_event(event.clone());
    }
    vm.run().expect("VM should not error");
    vm.output().clone()
}

#[test]
fn std_graph_phase1_calls_lower_to_graph_intrinsics() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(640, 480, 'Graph smoke');
  var Screen: Size := Application.Size(App);
  var Pending: Option of Event := Application.PollEvent(App);
    var Timed: Option of Event := Application.ReadEventTimeout(App, 16);
    Application.Clear(App, $00010203);
    Application.PutPixel(App, 1, 0, $00ABCDEF);
    Application.DrawLine(App, 0, 0, 3, 3, $00000010);
    Application.DrawRect(App, 1, 1, 2, 2, $00000020);
    Application.FillRect(App, 0, 0, 1, 1, $00000030);
    Application.DrawCircle(App, 3, 3, 1, $00000040);
        Application.DrawText(App, 0, 0, 'A', $00000050);
    Application.Present(App);
  var Pixels: array of integer := [$00102040, $00102040];
  Application.UploadFrame(App, 1, 2, Pixels);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationOpen))
        )),
        "expected Application.Open intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationSize))
        )),
        "expected Application.Size intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationPollEvent))
        )),
        "expected Application.PollEvent intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationReadEventTimeout))
        )),
        "expected Application.ReadEventTimeout intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationUploadFrame))
        )),
        "expected Application.UploadFrame intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationClose))
        )),
        "expected Application.Close intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationClear))
        )),
        "expected Application.Clear intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationPutPixel))
        )),
        "expected Application.PutPixel intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationPresent))
        )),
        "expected Application.Present intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawLine))
        )),
        "expected Application.DrawLine intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawRect))
        )),
        "expected Application.DrawRect intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationFillRect))
        )),
        "expected Application.FillRect intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawCircle))
        )),
        "expected Application.DrawCircle intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code)
                if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::ApplicationDrawText))
        )),
        "expected Application.DrawText intrinsic in generated bytecode"
    );
}

#[test]
fn std_graph_open_rejects_second_session() {
    with_headless(|| {
        let error = compile_run_error(
            "\
program T;
uses Std.Graph;

begin
  var First: Application := Application.Open(2, 2, 'Graph one');
  var Second: Application := Application.Open(3, 1, 'Graph two')
end.",
        );

        assert!(
            error
                .message
                .contains("cannot open a second graphics session"),
            "unexpected runtime error: {}",
            error.message
        );
    });
}

#[test]
fn std_graph_clear_rejects_invalid_rgb24_color() {
    with_headless(|| {
        let error = compile_run_error(
            "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(2, 2, 'Graph smoke');
  Application.Clear(App, $01000000)
end.",
        );

        assert!(
            error.message.contains("requires `$00RRGGBB` colors"),
            "unexpected runtime error: {}",
            error.message
        );
    });
}

#[test]
fn std_graph_open_rejects_wrong_argument_count_during_compilation() {
    let err = compile_err(
        "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(640, 480)
end.",
    );

    assert!(
        err.message.contains("expects 3 arguments"),
        "unexpected compiler error: {}",
        err.message
    );
}

#[test]
fn std_graph_phase1_runtime_bridge_supports_size_poll_upload_and_close() {
    with_headless(|| {
        let out = compile_and_run(
            "\
program T;
uses Std.Console, Std.Graph, Std.Option;

begin
    var App: Application := Application.Open(2, 2, 'Graph smoke');
  var Screen: Size := Application.Size(App);
  Std.Console.WriteLn(Screen.width);
  Std.Console.WriteLn(Screen.height);
  Std.Console.WriteLn(Std.Option.IsNone(Application.PollEvent(App)));
  var Pixels: array of integer := [$00102040, $00010203, $00000000, $00FFFFFF];
  Application.UploadFrame(App, 2, 2, Pixels);
  Application.Close(App)
end.",
        );

        assert_eq!(out.lines, vec!["2", "2", "true"]);
    });
}

#[test]
fn std_graph_read_event_timeout_returns_none_without_events() {
    with_headless(|| {
        let out = compile_and_run(
            "\
program T;
uses Std.Console, Std.Graph, Std.Option;

begin
  var App: Application := Application.Open(2, 2, 'Graph timeout');
  Std.Console.WriteLn(Std.Option.IsNone(Application.ReadEventTimeout(App, 0)));
  Application.Close(App)
end.",
        );

        assert_eq!(out.lines, vec!["true"]);
    });
}

#[test]
fn std_graph_read_event_timeout_returns_queued_resize_event() {
    with_headless(|| {
        let out = compile_run_with_graph_events(
            "\
program T;
uses Std.Console, Std.Conv, Std.Graph, Std.Option;

begin
  var App: Application := Application.Open(2, 2, 'Graph timeout');
  case Application.ReadEventTimeout(App, 16) of
    Some(E): Std.Console.WriteLn(IntToStr(E.size.width), 'x', IntToStr(E.size.height));
    None: Std.Console.WriteLn('none')
  end;
  Application.Close(App)
end.",
            &[GraphEvent::Resize {
                width: 120,
                height: 40,
            }],
        );

        assert_eq!(out.lines, vec!["120x40"]);
    });
}

#[test]
fn std_graph_poll_event_exposes_resize_and_close_requested_to_programs() {
    with_headless(|| {
        let out = compile_run_with_graph_events(
            "\
program T;
uses Std.Console, Std.Conv, Std.Graph, Std.Option;

begin
    var App: Application := Application.Open(2, 2, 'Graph events');

    case Application.PollEvent(App) of
        Some(E):
            Std.Console.WriteLn('resize=', IntToStr(E.size.width), 'x', IntToStr(E.size.height));
        None:
            Std.Console.WriteLn('missing-resize')
    end;

    case Application.PollEvent(App) of
        Some(E):
            Std.Console.WriteLn('event2=', IntToStr(E.size.width), 'x', IntToStr(E.size.height));
        None:
            Std.Console.WriteLn('missing-close')
    end;

    Application.Close(App)
end.",
            &[
                GraphEvent::Resize {
                    width: 320,
                    height: 200,
                },
                GraphEvent::CloseRequested,
            ],
        );

        assert_eq!(out.lines, vec!["resize=320x200", "event2=0x0"]);
    });
}

#[test]
fn std_graph_can_close_and_reopen_in_one_process_without_stale_state() {
    with_headless(|| {
        let out = compile_and_run(
            "\
program T;
uses Std.Console, Std.Conv, Std.Graph;

begin
  var First: Application := Application.Open(2, 2, 'Graph one');
  var FirstSize: Size := Application.Size(First);
  Std.Console.WriteLn(IntToStr(FirstSize.width), 'x', IntToStr(FirstSize.height));
  Application.Close(First);

  var Second: Application := Application.Open(3, 1, 'Graph two');
  var SecondSize: Size := Application.Size(Second);
  Std.Console.WriteLn(IntToStr(SecondSize.width), 'x', IntToStr(SecondSize.height));
  Application.Close(Second)
end.",
        );

        assert_eq!(out.lines, vec!["2x2", "3x1"]);
    });
}

#[test]
fn std_graph_clear_put_pixel_and_present_render_headless_frame() {
    with_headless(|| {
        let out = compile_and_run(
            "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(2, 1, 'Graph draw');
  Application.Clear(App, $00010203);
  Application.PutPixel(App, 1, 0, $00ABCDEF);
  Application.Present(App)
end.",
        );

        assert!(out.lines.is_empty(), "unexpected output: {:?}", out.lines);

        let frame = last_headless_graph_frame_for_tests()
            .expect("present should publish a headless frame snapshot");
        assert_eq!(frame.width(), 2);
        assert_eq!(frame.height(), 1);
        assert_eq!(frame.pixels(), &[0x00010203, 0x00ABCDEF]);
    });
}

#[test]
fn std_graph_draw_primitives_render_headless_frame() {
    with_headless(|| {
        let out = compile_and_run(
            "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(5, 5, 'Graph draw');
  Application.DrawLine(App, -1, 1, 3, 1, $00000001);
  Application.DrawRect(App, 1, 0, 3, 3, $00000002);
  Application.FillRect(App, 0, 4, 2, 1, $00000003);
  Application.DrawCircle(App, 3, 3, 1, $00000004);
  Application.Present(App)
end.",
        );

        assert!(out.lines.is_empty(), "unexpected output: {:?}", out.lines);

        let frame = last_headless_graph_frame_for_tests()
            .expect("present should publish a headless frame snapshot");
        assert_eq!(frame.width(), 5);
        assert_eq!(frame.height(), 5);
        assert_eq!(
            frame.pixels(),
            &[
                0, 0x00000002, 0x00000002, 0x00000002, 0, 0x00000001, 0x00000002, 0x00000001,
                0x00000002, 0, 0, 0x00000002, 0x00000002, 0x00000004, 0, 0, 0, 0x00000004, 0,
                0x00000004, 0x00000003, 0x00000003, 0, 0x00000004, 0,
            ]
        );
    });
}

#[test]
fn std_graph_draw_text_renders_headless_frame() {
    with_headless(|| {
        let out = compile_and_run(
            "\
program T;
uses Std.Graph;

begin
  var App: Application := Application.Open(5, 7, 'Graph text');
  Application.DrawText(App, 0, 0, 'A', $00000005);
  Application.Present(App)
end.",
        );

        assert!(out.lines.is_empty(), "unexpected output: {:?}", out.lines);

        let frame = last_headless_graph_frame_for_tests()
            .expect("present should publish a headless frame snapshot");
        assert_eq!(frame.width(), 5);
        assert_eq!(frame.height(), 7);
        assert_eq!(
            frame.pixels(),
            &[
                0, 0x00000005, 0x00000005, 0x00000005, 0, 0x00000005, 0, 0, 0, 0x00000005,
                0x00000005, 0, 0, 0, 0x00000005, 0x00000005, 0x00000005, 0x00000005, 0x00000005,
                0x00000005, 0x00000005, 0, 0, 0, 0x00000005, 0x00000005, 0, 0, 0, 0x00000005,
                0x00000005, 0, 0, 0, 0x00000005,
            ]
        );
    });
}

#[test]
fn std_graph_basics_example_runs_headless() {
    with_headless(|| {
        let out = compile_and_run(GRAPH_BASICS_EXAMPLE);

        assert_eq!(out.lines, vec!["size=32x24", "pending=false"]);

        let frame = last_headless_graph_frame_for_tests()
            .expect("present should publish a headless frame snapshot");
        assert_eq!(frame.width(), 32);
        assert_eq!(frame.height(), 24);
    });
}

#[test]
fn std_graph_julia_example_renders_one_headless_frame_then_exits_on_escape() {
    with_headless(|| {
        let out = compile_run_with_graph_events(
            JULIA_GRAPH_EXAMPLE,
            &[GraphEvent::Key(ConsoleKeyEvent::new(
                key_kind_index("Escape"),
                '\0',
                false,
                false,
                false,
                false,
            ))],
        );

        assert!(out.lines.is_empty(), "unexpected output: {:?}", out.lines);

        let frame = last_headless_graph_frame_for_tests()
            .expect("present should publish a headless frame snapshot");
        assert_eq!(frame.width(), 96);
        assert_eq!(frame.height(), 72);
        assert!(
            frame.pixels().iter().any(|pixel| *pixel != 0),
            "expected a non-empty Julia frame"
        );
    });
}

#[test]
fn std_graph_mandelbrot_example_renders_one_headless_frame_then_exits_on_escape() {
    with_headless(|| {
        let out = compile_run_with_graph_events(
            MANDELBROT_GRAPH_EXAMPLE,
            &[GraphEvent::Key(ConsoleKeyEvent::new(
                key_kind_index("Escape"),
                '\0',
                false,
                false,
                false,
                false,
            ))],
        );

        assert!(out.lines.is_empty(), "unexpected output: {:?}", out.lines);

        let frame = last_headless_graph_frame_for_tests()
            .expect("present should publish a headless frame snapshot");
        assert_eq!(frame.width(), 1280);
        assert_eq!(frame.height(), 800);
        assert!(
            frame.pixels().iter().any(|pixel| *pixel != 0),
            "expected a non-empty Mandelbrot frame"
        );
    });
}
