//! Compiler integration tests for headless native graph testing.
//!
//! **Documentation:** `docs/pascal/std/graph-app.md`, `docs/pascal/std/test.md`

use super::super::{compile_and_run, compile_ok};
use fpas_bytecode::intrinsic::GraphIntrinsic;
use fpas_bytecode::{Intrinsic, Op};

#[test]
fn std_graph_open_for_test_is_registered() {
    compile_ok(
        "\
program T;
uses Std.Graph;
begin
  var App: Application := Application.OpenForTest(32, 24);
  Application.Close(App)
end.",
    );
}

#[test]
fn std_graph_open_for_test_and_test_send_key_lower_to_intrinsics() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Graph;

begin
  var App: Application := Application.OpenForTest(32, 24);
  var EscapeKey: Std.Console.KeyEvent := record
    kind := Std.Console.KeyKind.Escape;
    ch := #27;
    shift := false;
    ctrl := false;
    alt := false;
    meta := false;
  end;
  Application.TestSendKey(App, EscapeKey);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::OpenForTest))
        )),
        "expected GraphOpenForTest intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Graph(GraphIntrinsic::TestSendKey))
        )),
        "expected GraphTestSendKey intrinsic in generated bytecode"
    );
}

#[test]
fn std_graph_open_for_test_rejects_non_positive_dimensions_at_runtime() {
    let message = super::super::compile_run_err(
        "\
program T;
uses Std.Graph;
begin
  var App: Application := Application.OpenForTest(0, 24);
  Application.Close(App)
end.",
    );
    assert!(message.contains("requires positive Width"));
}

#[test]
fn std_graph_smoke_style_test_runs() {
    let out = compile_and_run(
        "\
program G;
uses Std.Console, Std.Graph, Std.Test;

mutable var QuitSeen: boolean := false;

procedure OnPaint(App: Application);
begin
  Application.Clear(App, $00020408);
  Application.DrawText(App, 2, 2, 'FPAS', $00FFFFFF);
  Application.Present(App)
end;

function OnKeyPressed(App: Application; Key: KeyEvent): boolean;
begin
  if Key.kind = KeyKind.Escape then
  begin
    QuitSeen := true;
    Application.HostRequestQuit(App);
    return true
  end;
  return false
end;

begin
  var App: Application := Application.OpenForTest(32, 24);
  var EscapeKey: Std.Console.KeyEvent := record
    kind := Std.Console.KeyKind.Escape;
    ch := #27;
    shift := false;
    ctrl := false;
    alt := false;
    meta := false;
  end;
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.TestSendKey(App, EscapeKey);
  Application.Run(App);
  AssertTrue(QuitSeen)
end.",
    );

    assert!(out.lines.is_empty());
}
