//! Integration tests for Phase 7 Step 3: host-resolved command shortcuts.
//!
//! **Documentation:** `docs/pascal/std/tui-app.md` (from the repository root).

use super::super::{compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

#[test]
fn std_tui_command_shortcut_dispatches_on_command_before_on_key_pressed() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnCommand(App: Application; CommandId: integer);
begin
  Std.Console.WriteLn(CommandId);
  Application.HostRequestQuit(App)
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('key');
  return true
end;

begin
  var App: Application := Application.Open();
  var SaveKey: Std.Console.KeyEvent := record
    kind := Std.Console.KeyKind.Character;
    ch := 's';
    shift := false;
    ctrl := true;
    alt := false;
    meta := false;
  end;
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.HostRegisterOnCommand(App, OnCommand);
  Application.HostRegisterOnKeyPressed(App, OnKeyPressed);
  Application.HostBindCommand(App, SaveKey, 42);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Character"),
            's',
            false,
            true,
            false,
            false,
        ))],
    );

    assert_eq!(out.lines, vec!["paint", "42"]);
}

#[test]
fn std_tui_on_command_can_be_registered_via_application_handlers() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnCommand(App: Application; CommandId: integer);
begin
  Std.Console.WriteLn(CommandId);
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  var SaveKey: Std.Console.KeyEvent := record
    kind := Std.Console.KeyKind.Character;
    ch := 's';
    shift := false;
    ctrl := true;
    alt := false;
    meta := false;
  end;
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnCommand := Some(OnCommand);
  end;
  Application.Configure(App, Handlers);
  Application.HostBindCommand(App, SaveKey, 7);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Character"),
            's',
            false,
            true,
            false,
            false,
        ))],
    );

    assert_eq!(out.lines, vec!["paint", "7"]);
}

#[test]
fn std_tui_command_calls_lower_to_intrinsics() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnCommand(App: Application; CommandId: integer); begin end;

begin
  var App: Application := Application.Open();
  var SaveKey: Std.Console.KeyEvent := record
    kind := Std.Console.KeyKind.Character;
    ch := 's';
    shift := false;
    ctrl := true;
    alt := false;
    meta := false;
  end;
  Application.HostRegisterOnCommand(App, OnCommand);
  Application.HostBindCommand(App, SaveKey, 42);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostRegisterOnCommand as u16
        )),
        "expected TuiHostRegisterOnCommand intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostBindCommand as u16
        )),
        "expected TuiHostBindCommand intrinsic in generated bytecode"
    );
}
