use super::super::{compile_and_run, compile_err, compile_ok};
use fpas_bytecode::{Intrinsic, Op};

#[test]
fn std_tui_configure_run_uses_bundle_handlers() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OnExit(App: Application; Reason: ExitReason);
begin
  Std.Console.WriteLn(Reason)
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnExit := Some(OnExit);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint", "Std.Tui.ExitReason.UserQuit"]);
}

#[test]
fn std_tui_configure_replaces_previous_optional_handlers_with_defaults() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OldOnExit(App: Application; Reason: ExitReason);
begin
  Std.Console.WriteLn('old-exit')
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnExit(App, OldOnExit);
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint"]);
}

#[test]
fn std_tui_configure_negative_idle_interval_disables_idle_callbacks() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OnIdle(App: Application);
begin
  Std.Console.WriteLn('idle')
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnIdleMilliseconds := -5;
    OnIdle := Some(OnIdle);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint"]);
}

#[test]
fn std_tui_configure_requires_on_paint_field() {
    let err = compile_err(
        "\
program T;
uses Std.Tui;
begin
  var Handlers: ApplicationHandlers := record end
end.",
    );

    assert_eq!(err.code, fpas_diagnostics::codes::SEMA_MISSING_RECORD_FIELD);
}

#[test]
fn std_tui_application_configure_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

procedure OnPaint(App: Application);
begin
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
  end;
  Application.Configure(App, Handlers);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiApplicationConfigure as u16
        )),
        "expected Application.Configure intrinsic in generated bytecode"
    );
}
