//! Integration tests for Phase 7 Step 2: host-managed focus chain and `OnActivate`/`OnDeactivate`.
//!
//! **Documentation:** `docs/pascal/std/tui/app/README.md` (from the repository root).

use super::super::{compile_and_run, compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op, TuiIntrinsic};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

// --- OnActivate / OnDeactivate registration ---

#[test]
fn std_tui_on_activate_and_on_deactivate_can_be_registered_via_host_register() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Application.HostRequestQuit(App)
end;

procedure OnActivate(App: Application);
begin
  Std.Console.WriteLn('activate')
end;

procedure OnDeactivate(App: Application);
begin
  Std.Console.WriteLn('deactivate')
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.HostRegisterOnActivate(App, OnActivate);
  Application.HostRegisterOnDeactivate(App, OnDeactivate);
  Application.Run(App)
end.",
    );
    // No Tab events injected, so neither handler fires.
    assert_eq!(out.lines, Vec::<String>::new());
}

#[test]
fn std_tui_configure_accepts_on_activate_and_on_deactivate_fields() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Application.HostRequestQuit(App)
end;

procedure OnActivate(App: Application);
begin
  Std.Console.WriteLn('activate')
end;

procedure OnDeactivate(App: Application);
begin
  Std.Console.WriteLn('deactivate')
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnActivate := Some(OnActivate);
    OnDeactivate := Some(OnDeactivate);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );
    // No Tab events, no dispatch.
    assert_eq!(out.lines, Vec::<String>::new());
}

#[test]
fn std_tui_on_activate_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

procedure OnPaint(App: Application); begin end;
procedure OnActivate(App: Application); begin end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.HostRegisterOnActivate(App, OnActivate);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostRegisterOnActivate))
        )),
        "expected TuiHostRegisterOnActivate intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_on_deactivate_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

procedure OnPaint(App: Application); begin end;
procedure OnDeactivate(App: Application); begin end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.HostRegisterOnDeactivate(App, OnDeactivate);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostRegisterOnDeactivate))
        )),
        "expected TuiHostRegisterOnDeactivate intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_view_host_calls_lower_to_intrinsics() {
    let chunk = compile_ok(
        "\
    program T;
    uses Std.Tui;

    begin
      var App: Application := Application.Open();
      var ViewHandle: ViewId := Application.HostRegisterView(App, 0, 0, 10, 5);
      Application.HostSetViewRect(App, ViewHandle, 1, 2, 11, 6);
      Application.HostPushChildView(App, ViewHandle);
      Application.HostUnregisterView(App, ViewHandle);
      var Focused: Option of ViewId := Application.QueryFocusedViewId(App);
      Application.Close(App)
    end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostRegisterView))
        )),
        "expected TuiHostRegisterView intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostPushChildView))
        )),
        "expected TuiHostPushChildView intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostSetViewRect))
        )),
        "expected TuiHostSetViewRect intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostUnregisterView))
        )),
        "expected TuiHostUnregisterView intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::QueryFocusedViewId))
        )),
        "expected TuiQueryFocusedViewId intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_view_tree_calls_lower_to_intrinsics() {
    let chunk = compile_ok(
        "\
    program T;
    uses Std.Tui;

    procedure OnViewPaint(App: Application; ViewId: ViewId; Bounds: Std.Tui.Rect);
    begin
    end;

    begin
      var App: Application := Application.Open();
      var Parent: ViewId := Application.HostRegisterView(App, 10, 10, 20, 10);
      var Child: ViewId := Application.HostRegisterView(App, 0, 0, 1, 1);
      Application.HostSetViewParent(App, Child, Some(Parent));
      Application.HostRegisterOnViewPaint(App, Child, OnViewPaint);
      Application.Close(App)
    end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostSetViewParent))
        )),
        "expected TuiHostSetViewParent intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostRegisterOnViewPaint))
        )),
        "expected TuiHostRegisterOnViewPaint intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_register_view_returns_view_id_handles() {
    let out = compile_and_run(
        "\
    program T;
    uses Std.Console, Std.Tui;

    begin
      var App: Application := Application.Open();
      var A: ViewId := Application.HostRegisterView(App, 0, 0, 10, 5);
      var B: ViewId := Application.HostRegisterView(App, 10, 0, 10, 5);
      Std.Console.WriteLn(A);
      Std.Console.WriteLn(B);
      Application.Close(App)
    end.",
    );

    assert_eq!(out.lines, vec!["0", "1"]);
}

#[test]
fn std_tui_view_focus_can_be_seeded_via_host_calls() {
    let out = compile_run_with_console_events(
        "\
    program T;
    uses Std.Console, Std.Tui;

    procedure OnPaint(App: Application);
    begin
      Std.Console.WriteLn('paint')
    end;

    procedure OnActivate(App: Application);
    begin
      Std.Console.WriteLn(Application.QueryFocusedViewId(App));
      Application.HostRequestQuit(App)
    end;

    begin
      var App: Application := Application.Open();
      var First: ViewId := Application.HostRegisterView(App, 0, 0, 10, 5);
      var Second: ViewId := Application.HostRegisterView(App, 10, 0, 10, 5);
      Application.HostPushChildView(App, First);
      Application.HostPushChildView(App, Second);
      Application.HostRegisterOnPaint(App, OnPaint);
      Application.HostRegisterOnActivate(App, OnActivate);
      Application.Run(App)
    end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Tab"),
            '\t',
            false,
            false,
            false,
            false,
        ))],
    );

    assert_eq!(out.lines, vec!["paint", "Some(0)"]);
}

#[test]
fn std_tui_local_view_paint_can_drive_application_run() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnViewPaint(App: Application; ViewId: ViewId; Bounds: Std.Tui.Rect);
begin
  Std.Console.WriteLn(ViewId);
  Std.Console.WriteLn(Bounds.x);
  Std.Console.WriteLn(Bounds.y);
  Std.Console.WriteLn(Bounds.width);
  Std.Console.WriteLn(Bounds.height);
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  var Parent: ViewId := Application.HostRegisterView(App, 10, 10, 20, 10);
  var Child: ViewId := Application.HostRegisterView(App, 0, 0, 1, 1);
  Application.HostSetViewParent(App, Child, Some(Parent));
  Application.HostSetViewRect(App, Child, 2, 3, 4, 2);
  Application.HostRegisterOnViewPaint(App, Child, OnViewPaint);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["1", "12", "13", "4", "2"]);
}

// --- Tab falls through to OnKeyPressed when no views in the focus chain ---

#[test]
fn std_tui_tab_key_reaches_on_key_pressed_when_no_focusable_views() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('tab-key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Tab"),
            '\t',
            false,
            false,
            false,
            false,
        ))],
    );

    // No views in focus chain → Tab reaches OnKeyPressed.
    assert_eq!(out.lines, vec!["paint", "tab-key"]);
}

#[test]
fn std_tui_shift_tab_reaches_on_key_pressed_when_no_focusable_views() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('shift-tab-key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Tab"),
            '\t',
            true, // shift
            false,
            false,
            false,
        ))],
    );

    // No views in focus chain → Shift+Tab reaches OnKeyPressed.
    assert_eq!(out.lines, vec!["paint", "shift-tab-key"]);
}
