//! Integration tests for Phase 7 Step 4: host modal stack API.
//!
//! **Documentation:** `docs/pascal/std/tui-app.md` (from the repository root).

use super::super::{compile_and_run, compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

#[test]
fn std_tui_modal_depth_tracks_enter_and_leave() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  Application.HostEnterModal(App, 10);
  Application.HostEnterModal(App, 20);
  Std.Console.WriteLn(Application.HostModalDepth(App));
  Application.HostLeaveModal(App);
  Std.Console.WriteLn(Application.HostModalDepth(App));
  Application.Close(App)
end.",
    );

    assert_eq!(out.lines, vec!["2", "1"]);
}

#[test]
fn std_tui_modal_calls_lower_to_intrinsics() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  Application.HostEnterModal(App, 10);
  Std.Console.WriteLn(Application.HostModalDepth(App));
  Application.HostLeaveModal(App);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostEnterModal as u16
        )),
        "expected TuiHostEnterModal intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostLeaveModal as u16
        )),
        "expected TuiHostLeaveModal intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostModalDepth as u16
        )),
        "expected TuiHostModalDepth intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_attach_view_to_active_modal_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

begin
  var App: Application := Application.Open();
  var ViewId: integer := Application.HostRegisterView(App, 0, 0, 10, 5);
  Application.HostEnterModal(App, 10);
  Application.HostAttachViewToActiveModal(App, ViewId);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostAttachViewToActiveModal as u16
        )),
        "expected TuiHostAttachViewToActiveModal intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_modal_scope_limits_tab_focus_to_attached_views() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  var Background: integer := Application.HostRegisterView(App, 0, 0, 5, 5);
  var DialogA: integer := Application.HostRegisterView(App, 10, 10, 5, 5);
  var DialogB: integer := Application.HostRegisterView(App, 20, 10, 5, 5);
  Application.HostPushChildView(App, Background);
  Application.HostPushChildView(App, DialogA);
  Application.HostPushChildView(App, DialogB);
  Application.HostEnterModal(App, 10);
  Application.HostAttachViewToActiveModal(App, DialogA);
  Application.HostAttachViewToActiveModal(App, DialogB);
  Std.Console.WriteLn(Application.HostProcessNext(App, 64));
  Std.Console.WriteLn(Application.HostQueryFocusedViewId(App));
  Application.Close(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Tab"),
            '\t',
            false,
            false,
            false,
            false,
        ))],
    );

    assert_eq!(out.lines, vec!["14", "1"]);
}

#[test]
fn std_tui_modal_scope_blocks_mouse_outside_attached_views() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnMouse(App: Application; Event: Std.Console.Event);
begin
  Std.Console.WriteLn('mouse')
end;

begin
  var App: Application := Application.Open();
  var Dialog: integer := Application.HostRegisterView(App, 10, 10, 5, 5);
  Application.HostRegisterOnMouse(App, OnMouse);
  Application.HostEnterModal(App, 10);
  Application.HostAttachViewToActiveModal(App, Dialog);
  Std.Console.WriteLn(Application.HostProcessNext(App, 64));
  Application.Close(App)
end.",
        &[ConsoleEvent::mouse(
            fpas_std::mouse_action_index("Down"),
            fpas_std::mouse_button_index("Left"),
            1,
            1,
            false,
            false,
            false,
            false,
        )],
    );

    assert_eq!(out.lines, vec!["19"]);
}

#[test]
fn std_tui_modal_scope_blocks_command_when_focus_is_outside_attached_views() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnCommand(App: Application; CommandId: integer);
begin
  Std.Console.WriteLn(CommandId)
end;

begin
  var App: Application := Application.Open();
  var SaveKey: Std.Console.KeyEvent := record
    kind := Std.Console.KeyKind.Character;
    ch := 's';
    shift := false;
    ctrl := true;
    alt := false;
    meta := false;
  end;
  var Background: integer := Application.HostRegisterView(App, 0, 0, 5, 5);
  var Dialog: integer := Application.HostRegisterView(App, 10, 10, 5, 5);
  Application.HostPushChildView(App, Background);
  Application.HostPushChildView(App, Dialog);
  Std.Console.WriteLn(Application.HostProcessNext(App, 64));
  Application.HostRegisterOnCommand(App, OnCommand);
  Application.HostBindCommand(App, SaveKey, 42);
  Application.HostEnterModal(App, 10);
  Application.HostAttachViewToActiveModal(App, Dialog);
  Std.Console.WriteLn(Application.HostProcessNext(App, 64));
  Application.Close(App)
end.",
        &[
            ConsoleEvent::key(ConsoleKeyEvent::new(
                key_kind_index("Tab"),
                '\t',
                false,
                false,
                false,
                false,
            )),
            ConsoleEvent::key(ConsoleKeyEvent::new(
                key_kind_index("Character"),
                's',
                false,
                true,
                false,
                false,
            )),
        ],
    );

    assert_eq!(out.lines, vec!["14", "20"]);
}
