use super::super::{compile_and_run, compile_err, compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

#[test]
fn std_tui_configure_run_uses_bundle_handlers() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OnExit(App: Application; Reason: ExitReason);
begin
  Std.Console.WriteLn(Reason)
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnExit := Some(OnExit);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint", "Std.Tui.ExitReason.UserQuit"]);
}

#[test]
fn std_tui_configure_replaces_previous_optional_handlers_with_defaults() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OldOnExit(App: Application; Reason: ExitReason);
begin
  Std.Console.WriteLn('old-exit')
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnExit(App, OldOnExit);
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint"]);
}

#[test]
fn std_tui_configure_negative_idle_interval_disables_idle_callbacks() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OnIdle(App: Application);
begin
  Std.Console.WriteLn('idle')
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnIdleMilliseconds := -5;
    OnIdle := Some(OnIdle);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint"]);
}

#[test]
fn std_tui_configure_requires_on_paint_field() {
    let err = compile_err(
        "\
program T;
uses Std.Tui;
begin
  var Handlers: ApplicationHandlers := record end
end.",
    );

    assert_eq!(err.code, fpas_diagnostics::codes::SEMA_MISSING_RECORD_FIELD);
}

#[test]
fn std_tui_application_configure_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

procedure OnPaint(App: Application);
begin
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
  end;
  Application.Configure(App, Handlers);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiApplicationConfigure as u16
        )),
        "expected Application.Configure intrinsic in generated bytecode"
    );
}

// Phase 5: dispatch model integration tests (key and resize events via Configure+Run).

#[test]
fn std_tui_configure_on_key_pressed_dispatches_key_event_and_quits() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Character"),
            'a',
            false,
            false,
            false,
            false,
        ))],
    );

    assert_eq!(out.lines, vec!["paint", "key"]);
}

#[test]
fn std_tui_configure_on_resize_dispatches_and_triggers_repaint() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnResize(App: Application; NewSize: Size);
begin
  Std.Console.WriteLn('resize');
  Application.RequestRedraw(App)
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnResize := Some(OnResize);
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[
            ConsoleEvent::resize(100, 50),
            ConsoleEvent::key(ConsoleKeyEvent::new(
                key_kind_index("Escape"),
                '\u{1b}',
                false,
                false,
                false,
                false,
            )),
        ],
    );

    assert_eq!(out.lines, vec!["resize", "paint", "key"]);
}

// Phase 6: OnMouse dispatch via Configure+Run.

#[test]
fn std_tui_configure_on_mouse_dispatches_mouse_event_and_quits() {
    use fpas_std::{mouse_action_index, mouse_button_index};

    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnMouse(App: Application; Event: Std.Console.Event);
begin
  Std.Console.WriteLn('mouse');
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnMouse := Some(OnMouse);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::mouse(
            mouse_action_index("Down"),
            mouse_button_index("Left"),
            10,
            5,
            false,
            false,
            false,
            false,
        )],
    );

    assert_eq!(out.lines, vec!["paint", "mouse"]);
}

#[test]
fn std_tui_configure_on_mouse_receives_correct_coordinates() {
    use fpas_std::{mouse_action_index, mouse_button_index};

    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
end;

procedure OnMouse(App: Application; Event: Std.Console.Event);
begin
  Std.Console.WriteLn(Event.mouse_x);
  Std.Console.WriteLn(Event.mouse_y);
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnMouse(App, OnMouse);
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.Run(App)
end.",
        &[ConsoleEvent::mouse(
            mouse_action_index("Move"),
            mouse_button_index("None"),
            42,
            17,
            false,
            false,
            false,
            false,
        )],
    );

    assert_eq!(out.lines, vec!["42", "17"]);
}

// Phase 6: OnPaste dispatch via Configure+Run.

#[test]
fn std_tui_configure_on_paste_dispatches_paste_event_and_quits() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnPaste(App: Application; Event: Std.Console.Event);
begin
  Std.Console.WriteLn('paste');
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnPaste := Some(OnPaste);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::paste("hello world".to_string())],
    );

    assert_eq!(out.lines, vec!["paint", "paste"]);
}

#[test]
fn std_tui_configure_on_paste_receives_text_content() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
end;

procedure OnPaste(App: Application; Event: Std.Console.Event);
begin
  Std.Console.WriteLn(Event.text);
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnPaste(App, OnPaste);
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.Run(App)
end.",
        &[ConsoleEvent::paste("copied text".to_string())],
    );

    assert_eq!(out.lines, vec!["copied text"]);
}

// Phase 6: OnFocusGained/OnFocusLost dispatch via Configure+Run.

#[test]
fn std_tui_configure_on_focus_gained_dispatches_event_and_quits() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnFocusGained(App: Application; Event: Std.Console.Event);
begin
  Std.Console.WriteLn('focused');
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnFocusGained := Some(OnFocusGained);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::focus_gained()],
    );

    assert_eq!(out.lines, vec!["paint", "focused"]);
}

#[test]
fn std_tui_configure_on_focus_lost_dispatches_event_and_quits() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnFocusLost(App: Application; Event: Std.Console.Event);
begin
  Std.Console.WriteLn('blurred');
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnFocusLost(App, OnFocusLost);
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.Run(App)
end.",
        &[ConsoleEvent::focus_lost()],
    );

    assert_eq!(out.lines, vec!["paint", "blurred"]);
}
