//! Integration tests for Phase 7 Step 4: host modal stack API.
//!
//! **Documentation:** `docs/pascal/std/tui-app.md` (from the repository root).

use super::super::{compile_and_run, compile_ok};
use fpas_bytecode::{Intrinsic, Op};

#[test]
fn std_tui_modal_depth_tracks_enter_and_leave() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  Application.HostEnterModal(App, 10);
  Application.HostEnterModal(App, 20);
  Std.Console.WriteLn(Application.HostModalDepth(App));
  Application.HostLeaveModal(App);
  Std.Console.WriteLn(Application.HostModalDepth(App));
  Application.Close(App)
end.",
    );

    assert_eq!(out.lines, vec!["2", "1"]);
}

#[test]
fn std_tui_modal_calls_lower_to_intrinsics() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  Application.HostEnterModal(App, 10);
  Std.Console.WriteLn(Application.HostModalDepth(App));
  Application.HostLeaveModal(App);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostEnterModal as u16
        )),
        "expected TuiHostEnterModal intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostLeaveModal as u16
        )),
        "expected TuiHostLeaveModal intrinsic in generated bytecode"
    );
    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostModalDepth as u16
        )),
        "expected TuiHostModalDepth intrinsic in generated bytecode"
    );
}
