//! Integration tests for Rust-hosted TUI widgets.
//!
//! **Documentation:** `docs/pascal/std/tui-app.md` (from the repository root).

use super::super::{compile_and_run, compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op, TuiIntrinsic};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

#[test]
fn std_tui_host_create_solid_fill_view_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  var ViewId: integer := Application.HostCreateSolidFillView(
    App, 0, 0, 10, 5, Blue, None, None);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostCreateSolidFillView))
        )),
        "expected TuiHostCreateSolidFillView intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_solid_fill_view_can_drive_application_run() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Desktop: integer := Application.HostCreateSolidFillView(
    App, 0, 0, 80, 25, Blue, None, None);
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Escape"),
            '\u{1b}',
            false,
            false,
            false,
            false,
        ))],
    );

    assert!(out.lines.is_empty());
}

#[test]
fn std_tui_solid_fill_view_returns_incrementing_handles() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  var A: integer := Application.HostCreateSolidFillView(App, 0, 0, 10, 5, Blue, None, None);
  var B: integer := Application.HostCreateSolidFillView(App, 10, 0, 10, 5, LightBlue, None, None);
  WriteLn(A);
  WriteLn(B);
  Application.Close(App)
end.",
    );

    assert_eq!(out.lines, vec!["0", "1"]);
}
