//! Integration tests for Phase 7 Step 2: host-managed focus chain and `OnActivate`/`OnDeactivate`.
//!
//! **Documentation:** `docs/pascal/std/tui-app.md` (from the repository root).

use super::super::{compile_and_run, compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

// --- OnActivate / OnDeactivate registration ---

#[test]
fn std_tui_on_activate_and_on_deactivate_can_be_registered_via_host_register() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Application.HostRequestQuit(App)
end;

procedure OnActivate(App: Application);
begin
  Std.Console.WriteLn('activate')
end;

procedure OnDeactivate(App: Application);
begin
  Std.Console.WriteLn('deactivate')
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.HostRegisterOnActivate(App, OnActivate);
  Application.HostRegisterOnDeactivate(App, OnDeactivate);
  Application.Run(App)
end.",
    );
    // No Tab events injected, so neither handler fires.
    assert_eq!(out.lines, Vec::<String>::new());
}

#[test]
fn std_tui_configure_accepts_on_activate_and_on_deactivate_fields() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Application.HostRequestQuit(App)
end;

procedure OnActivate(App: Application);
begin
  Std.Console.WriteLn('activate')
end;

procedure OnDeactivate(App: Application);
begin
  Std.Console.WriteLn('deactivate')
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnActivate := Some(OnActivate);
    OnDeactivate := Some(OnDeactivate);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );
    // No Tab events, no dispatch.
    assert_eq!(out.lines, Vec::<String>::new());
}

#[test]
fn std_tui_on_activate_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

procedure OnPaint(App: Application); begin end;
procedure OnActivate(App: Application); begin end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.HostRegisterOnActivate(App, OnActivate);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostRegisterOnActivate as u16
        )),
        "expected TuiHostRegisterOnActivate intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_on_deactivate_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

procedure OnPaint(App: Application); begin end;
procedure OnDeactivate(App: Application); begin end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnPaint(App, OnPaint);
  Application.HostRegisterOnDeactivate(App, OnDeactivate);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiHostRegisterOnDeactivate as u16
        )),
        "expected TuiHostRegisterOnDeactivate intrinsic in generated bytecode"
    );
}

// --- Tab falls through to OnKeyPressed when no views in the focus chain ---

#[test]
fn std_tui_tab_key_reaches_on_key_pressed_when_no_focusable_views() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('tab-key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Tab"),
            '\t',
            false,
            false,
            false,
            false,
        ))],
    );

    // No views in focus chain → Tab reaches OnKeyPressed.
    assert_eq!(out.lines, vec!["paint", "tab-key"]);
}

#[test]
fn std_tui_shift_tab_reaches_on_key_pressed_when_no_focusable_views() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('shift-tab-key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Tab"),
            '\t',
            true, // shift
            false,
            false,
            false,
        ))],
    );

    // No views in focus chain → Shift+Tab reaches OnKeyPressed.
    assert_eq!(out.lines, vec!["paint", "shift-tab-key"]);
}
