use super::super::{compile_and_run, compile_err, compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

#[test]
fn std_tui_configure_run_uses_bundle_handlers() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OnExit(App: Application; Reason: ExitReason);
begin
  Std.Console.WriteLn(Reason)
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnExit := Some(OnExit);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint", "Std.Tui.ExitReason.UserQuit"]);
}

#[test]
fn std_tui_configure_replaces_previous_optional_handlers_with_defaults() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OldOnExit(App: Application; Reason: ExitReason);
begin
  Std.Console.WriteLn('old-exit')
end;

begin
  var App: Application := Application.Open();
  Application.HostRegisterOnExit(App, OldOnExit);
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint"]);
}

#[test]
fn std_tui_configure_negative_idle_interval_disables_idle_callbacks() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint');
  Application.HostRequestQuit(App)
end;

procedure OnIdle(App: Application);
begin
  Std.Console.WriteLn('idle')
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnIdleMilliseconds := -5;
    OnIdle := Some(OnIdle);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
    );

    assert_eq!(out.lines, vec!["paint"]);
}

#[test]
fn std_tui_configure_requires_on_paint_field() {
    let err = compile_err(
        "\
program T;
uses Std.Tui;
begin
  var Handlers: ApplicationHandlers := record end
end.",
    );

    assert_eq!(err.code, fpas_diagnostics::codes::SEMA_MISSING_RECORD_FIELD);
}

#[test]
fn std_tui_application_configure_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Tui;

procedure OnPaint(App: Application);
begin
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
  end;
  Application.Configure(App, Handlers);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
            op,
            Op::Intrinsic(code) if *code == Intrinsic::TuiApplicationConfigure as u16
        )),
        "expected Application.Configure intrinsic in generated bytecode"
    );
}

// Phase 5: dispatch model integration tests (key and resize events via Configure+Run).

#[test]
fn std_tui_configure_on_key_pressed_dispatches_key_event_and_quits() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Character"),
            'a',
            false,
            false,
            false,
            false,
        ))],
    );

    assert_eq!(out.lines, vec!["paint", "key"]);
}

#[test]
fn std_tui_configure_on_resize_dispatches_and_triggers_repaint() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
  Std.Console.WriteLn('paint')
end;

procedure OnResize(App: Application; NewSize: Size);
begin
  Std.Console.WriteLn('resize');
  Application.RequestRedraw(App)
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Std.Console.WriteLn('key');
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Handlers: ApplicationHandlers := record
    OnPaint := OnPaint;
    OnResize := Some(OnResize);
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[
            ConsoleEvent::resize(100, 50),
            ConsoleEvent::key(ConsoleKeyEvent::new(
                key_kind_index("Escape"),
                '\u{1b}',
                false,
                false,
                false,
                false,
            )),
        ],
    );

    assert_eq!(out.lines, vec!["paint", "resize", "paint", "key"]);
}

