//! Integration tests for Rust-hosted TUI widgets.
//!
//! **Documentation:** `docs/pascal/std/tui/app/README.md` (from the repository root).

use super::super::{compile_and_run, compile_ok, compile_run_with_console_events};
use fpas_bytecode::{Intrinsic, Op, TuiIntrinsic};
use fpas_std::{ConsoleEvent, ConsoleKeyEvent, key_event::key_kind_index};

#[test]
fn std_tui_host_create_solid_fill_view_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  var Handle: ViewId := Application.HostCreateSolidFillView(
    App, 0, 0, 10, 5, Blue, None, None);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostCreateSolidFillView))
        )),
        "expected TuiHostCreateSolidFillView intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_solid_fill_view_can_drive_application_run() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

procedure OnPaint(App: Application);
begin
end;

function OnKeyPressed(App: Application; Key: Std.Console.KeyEvent): boolean;
begin
  Application.HostRequestQuit(App);
  return true
end;

begin
  var App: Application := Application.Open();
  var Desktop: ViewId := Application.HostCreateSolidFillView(
    App, 0, 0, 80, 25, Blue, None, None);
  var Handlers: ApplicationHandlers := record
    OnPaint := Some(OnPaint);
    OnKeyPressed := Some(OnKeyPressed);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[ConsoleEvent::key(ConsoleKeyEvent::new(
            key_kind_index("Escape"),
            '\u{1b}',
            false,
            false,
            false,
            false,
        ))],
    );

    assert!(out.lines.is_empty());
}

#[test]
fn std_tui_solid_fill_view_returns_incrementing_handles() {
    let out = compile_and_run(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  var A: ViewId := Application.HostCreateSolidFillView(App, 0, 0, 10, 5, Blue, None, None);
  var B: ViewId := Application.HostCreateSolidFillView(App, 10, 0, 10, 5, LightBlue, None, None);
  WriteLn(A);
  WriteLn(B);
  Application.Close(App)
end.",
    );

    assert_eq!(out.lines, vec!["0", "1"]);
}

#[test]
fn std_tui_host_create_menu_bar_view_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  var Items: array of MenuBarItem := [
    record Label := 'File'; Shortcut := 'F'; Enabled := true; CommandId := 1; Submenu := []; end
  ];
  var Style: MenuBarStyle := record
    BarBg := LightGray;
    BarFg := Black;
    AccelFg := Red;
    HighlightBg := Black;
    HighlightFg := LightGray;
    DisabledFg := DarkGray;
  end;
  var Handle: ViewId := Application.HostCreateMenuBarView(
    App, 0, 0, 80, 1, Items, Style);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostCreateMenuBarView))
        )),
        "expected TuiHostCreateMenuBarView intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_host_create_status_bar_view_lowers_to_intrinsic() {
    let chunk = compile_ok(
        "\
program T;
uses Std.Console, Std.Tui;

begin
  var App: Application := Application.Open();
  var Segments: array of StatusBarSegment := [
    record Text := 'Ln 1'; AlignRight := true; end
  ];
  var Style: StatusBarStyle := record
    BarBg := LightGray;
    BarFg := Black;
  end;
  var Handle: ViewId := Application.HostCreateStatusBarView(
    App, 0, 24, 80, 1, Segments, Style);
  Application.Close(App)
end.",
    );

    assert!(
        chunk.code.iter().any(|op| matches!(
          op,
          Op::Intrinsic(code) if *code == u16::from(Intrinsic::Tui(TuiIntrinsic::HostCreateStatusBarView))
        )),
        "expected TuiHostCreateStatusBarView intrinsic in generated bytecode"
    );
}

#[test]
fn std_tui_menu_bar_alt_shortcut_opens_submenu_and_exit() {
    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

function FileSubmenu(): array of MenuPopupItem;
begin
  return [
    record Label := 'Exit'; Shortcut := 'X'; Enabled := true; CommandId := 1; Separator := false; end
  ]
end;

function MenuItems(): array of MenuBarItem;
begin
  return [
    record
      Label := 'File'; Shortcut := 'F'; Enabled := true; CommandId := -1;
      Submenu := FileSubmenu();
    end
  ]
end;

function MenuStyle(): MenuBarStyle;
begin
  return record
    BarBg := LightGray;
    BarFg := Black;
    AccelFg := Red;
    HighlightBg := Black;
    HighlightFg := LightGray;
    DisabledFg := DarkGray;
  end
end;

procedure OnPaint(App: Application);
begin
end;

procedure OnCommand(App: Application; CommandId: integer);
begin
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  var MenuBar: ViewId := Application.HostCreateMenuBarView(
    App, 0, 0, 80, 1, MenuItems(), MenuStyle());
  var Handlers: ApplicationHandlers := record
    OnPaint := Some(OnPaint);
    OnCommand := Some(OnCommand);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[
            ConsoleEvent::key(ConsoleKeyEvent::new(
                key_kind_index("Character"),
                'f',
                false,
                false,
                true,
                false,
            )),
            ConsoleEvent::key(ConsoleKeyEvent::new(
                key_kind_index("Enter"),
                '\0',
                false,
                false,
                false,
                false,
            )),
        ],
    );

    assert!(out.lines.is_empty());
}

#[test]
fn std_tui_menu_bar_mouse_click_dispatches_on_command_over_desktop() {
    use fpas_std::{mouse_action_index, mouse_button_index};

    let out = compile_run_with_console_events(
        "\
program T;
uses Std.Console, Std.Tui;

function FileSubmenu(): array of MenuPopupItem;
begin
  return [
    record Label := 'Open...'; Shortcut := 'O'; Enabled := false; CommandId := -1; Separator := false; end,
    record Label := ''; Shortcut := #0; Enabled := false; CommandId := -1; Separator := true; end,
    record Label := 'Exit'; Shortcut := 'X'; Enabled := true; CommandId := 1; Separator := false; end
  ]
end;

function MenuItems(): array of MenuBarItem;
begin
  return [
    record
      Label := 'File'; Shortcut := 'F'; Enabled := true; CommandId := -1;
      Submenu := FileSubmenu();
    end
  ]
end;

function MenuStyle(): MenuBarStyle;
begin
  return record
    BarBg := LightGray;
    BarFg := Black;
    AccelFg := Red;
    HighlightBg := Black;
    HighlightFg := LightGray;
    DisabledFg := DarkGray;
  end
end;

procedure OnPaint(App: Application);
begin
end;

procedure OnCommand(App: Application; CommandId: integer);
begin
  Application.HostRequestQuit(App)
end;

begin
  var App: Application := Application.Open();
  var MenuBar: ViewId := Application.HostCreateMenuBarView(
    App, 0, 0, 80, 1, MenuItems(), MenuStyle());
  var Desktop: ViewId := Application.HostCreateSolidFillView(
    App, 0, 1, 80, 24, Blue, None, None);
  var Handlers: ApplicationHandlers := record
    OnPaint := Some(OnPaint);
    OnCommand := Some(OnCommand);
  end;
  Application.Configure(App, Handlers);
  Application.Run(App)
end.",
        &[
            ConsoleEvent::mouse(
                mouse_action_index("Down"),
                mouse_button_index("Left"),
                2,
                1,
                false,
                false,
                false,
                false,
            ),
            ConsoleEvent::mouse(
                mouse_action_index("Down"),
                mouse_button_index("Left"),
                2,
                5,
                false,
                false,
                false,
                false,
            ),
        ],
    );

    assert!(out.lines.is_empty());
}
