[package]
name = "fpas-linker"
description = "Deterministic linker from Functional Pascal unit objects to executable chunks"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fpas-bytecode = { path = "../fpas-bytecode" }
fpas-unit = { path = "../fpas-unit" }

[dev-dependencies]
fpas-vm = { path = "../fpas-vm" }

[lints]
workspace = true
