use super::*;

mod bound_methods;
mod build;
mod check;
mod dependencies;
mod edge_cases;
mod enum_variants;
mod errors;
mod exports;
mod generic_aliases;
mod qualified;
mod record_events;
mod record_properties;
mod resolution;
mod run;
mod support;
mod warnings;
mod workspace_run;
