use super::Token;

impl Token {
    /// Creates a keyword token when `raw` matches a Pascal keyword.
    ///
    /// Returns [`Token::Ident`] for non-keyword identifiers.
    #[must_use]
    pub fn from_ident(raw: &str) -> Token {
        match raw {
            s if s.eq_ignore_ascii_case("program") => Token::Program,
            s if s.eq_ignore_ascii_case("unit") => Token::Unit,
            s if s.eq_ignore_ascii_case("uses") => Token::Uses,
            s if s.eq_ignore_ascii_case("const") => Token::Const,
            s if s.eq_ignore_ascii_case("var") => Token::Var,
            s if s.eq_ignore_ascii_case("mutable") => Token::Mutable,
            s if s.eq_ignore_ascii_case("function") => Token::Function,
            s if s.eq_ignore_ascii_case("procedure") => Token::Procedure,
            s if s.eq_ignore_ascii_case("begin") => Token::Begin,
            s if s.eq_ignore_ascii_case("end") => Token::End,
            s if s.eq_ignore_ascii_case("return") => Token::Return,
            s if s.eq_ignore_ascii_case("if") => Token::If,
            s if s.eq_ignore_ascii_case("then") => Token::Then,
            s if s.eq_ignore_ascii_case("else") => Token::Else,
            s if s.eq_ignore_ascii_case("case") => Token::Case,
            s if s.eq_ignore_ascii_case("of") => Token::Of,
            s if s.eq_ignore_ascii_case("for") => Token::For,
            s if s.eq_ignore_ascii_case("to") => Token::To,
            s if s.eq_ignore_ascii_case("downto") => Token::Downto,
            s if s.eq_ignore_ascii_case("in") => Token::In,
            s if s.eq_ignore_ascii_case("do") => Token::Do,
            s if s.eq_ignore_ascii_case("while") => Token::While,
            s if s.eq_ignore_ascii_case("repeat") => Token::Repeat,
            s if s.eq_ignore_ascii_case("until") => Token::Until,
            s if s.eq_ignore_ascii_case("and") => Token::And,
            s if s.eq_ignore_ascii_case("or") => Token::Or,
            s if s.eq_ignore_ascii_case("not") => Token::Not,
            s if s.eq_ignore_ascii_case("xor") => Token::Xor,
            s if s.eq_ignore_ascii_case("div") => Token::Div,
            s if s.eq_ignore_ascii_case("mod") => Token::Mod,
            s if s.eq_ignore_ascii_case("shl") => Token::Shl,
            s if s.eq_ignore_ascii_case("shr") => Token::Shr,
            s if s.eq_ignore_ascii_case("true") => Token::True,
            s if s.eq_ignore_ascii_case("false") => Token::False,
            s if s.eq_ignore_ascii_case("type") => Token::Type,
            s if s.eq_ignore_ascii_case("record") => Token::Record,
            s if s.eq_ignore_ascii_case("enum") => Token::Enum,
            s if s.eq_ignore_ascii_case("array") => Token::Array,
            s if s.eq_ignore_ascii_case("panic") => Token::Panic,
            s if s.eq_ignore_ascii_case("break") => Token::Break,
            s if s.eq_ignore_ascii_case("continue") => Token::Continue,
            s if s.eq_ignore_ascii_case("public") => Token::Public,
            s if s.eq_ignore_ascii_case("private") => Token::Private,
            s if s.eq_ignore_ascii_case("result") => Token::Result,
            s if s.eq_ignore_ascii_case("option") => Token::OptionKw,
            s if s.eq_ignore_ascii_case("ok") => Token::Ok,
            s if s.eq_ignore_ascii_case("error") => Token::Error,
            s if s.eq_ignore_ascii_case("some") => Token::Some,
            s if s.eq_ignore_ascii_case("none") => Token::None,
            s if s.eq_ignore_ascii_case("try") => Token::Try,
            s if s.eq_ignore_ascii_case("go") => Token::Go,
            s if s.eq_ignore_ascii_case("dict") => Token::Dict,
            s if s.eq_ignore_ascii_case("with") => Token::With,
            _ => Token::Ident(raw.to_owned()),
        }
    }
}
